### ISSUE TITLE
add 3rd party core setting

### ISSUE THREAD

**Issue by Master811129** [arduino/arduino-pro-ide#10]
hello there please add the core settings to the new IDE like the old IDE (1.8.9)
![image](https://user-images.githubusercontent.com/37829730/67148550-748a5e80-f2ad-11e9-959e-a369706fabc6.png)
thanks

**Comment by wero1414** [comment]
I was just tu put this issue

**Comment by Master811129** [comment]
#10

**Comment by Master811129** [comment]
![image](https://user-images.githubusercontent.com/37829730/81055423-e76fc580-8edd-11ea-8c9a-7b21cb0307cc.png)

now it works on Windows well.
