### ISSUE TITLE
Sketch is lost when changing from classic to adva

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#101]
**Describe the bug**
When changing from classic to advanced mode the sketch is lost, I have an empty space.
When I load a sketch in advanced and go the classic the sketch in classic was the one before,
not the currently loaded in advanced.

**To Reproduce**
- sketch is loaded in classic mode
- switch to advanced 

**Expected behavior**
The sketch should hold when switching to advanced

**Screenshots**
<img width="1232" alt="classic" src="https://user-images.githubusercontent.com/6450325/67592602-6f6f5880-f760-11e9-87cf-f3a27f678cc7.png">
<img width="1232" alt="advanced" src="https://user-images.githubusercontent.com/6450325/67592607-71d1b280-f760-11e9-8f41-a2277d8b4a43.png">

**Desktop (please complete the following information):**
 - OS macOS Catalina
 - Version 0.0.2

**Comment by Master811129** [comment]
yeah i also see it in windows 10.

**Comment by kittaakos** [comment]
Thanks for reporting it, @sstaub.

This is a glitch we are working on; the editors are not restored between the sessions. As a workaround, you can click on the `Explorer` icon on the left side-bar (or <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>E</kbd>) and open your sketch file manually. Please reference the attached screencast:

![screencast 2019-11-12 10-40-20](https://user-images.githubusercontent.com/1405703/68660465-7f957f00-0539-11ea-9a74-e5410534f478.gif)

**Comment by kittaakos** [comment]
Upstream issue: https://github.com/eclipse-theia/theia/issues/6530
