### ISSUE TITLE
Naming convention when saving projects

### ISSUE THREAD

**Issue by MatsK** [arduino/arduino-pro-ide#110]
**Is your feature request related to a problem? Please describe.**
When I save a project with default naming is hard to see which year it is saved and is conflicting if you work with projects over several years:
**Example folder name:** sketch_apr16a

**Describe the solution you'd like**
To change the naming suggestion to YYYY-MM-DD would 
**Example folder name would be:** sketch_2018-04-16a

**Comment by ubidefeo** [comment]
@MatsK as someone who has about 200 sketches built on Arduino, some of them from 10 years ago, I doubt I would be able to track anything down were I to save them with default name.
This seems to me like a non-issue.
We're in the process of cleaning up the backlog, if you feel strongly about this please feel free to reopen it.
Thank you for understanding 🙏🏼
