### ISSUE TITLE
How to Setup on Debian Stretch?

### ISSUE THREAD

**Issue by harryberlin** [arduino/arduino-pro-ide#111]
Tried the Linux Version. After running the arduino-electr.... file, there was only the sandclock and than nothing.

**Comment by mastrolinux** [comment]
Please try the latest v0.0.2 version and let me know

**Comment by harryberlin** [comment]
where to find the how to?

**Comment by cmaglie** [comment]
https://github.com/arduino/arduino-pro-ide/releases

**Comment by harryberlin** [comment]
there is only the release download. no manual for install on debian.

tried the windows version:
folder loading is ok.
after opening i get some error notifications. something like failed to start language server, unexpected git executable.
couldn't start the client arduino.
the ide forget the selected board.
i have installed the library SimpleTimer but the compiler shows lot of errors.
how to install libraries from zip?
how to select the nano bootloader versions?
at the end:
i like the old ide :)
