### ISSUE TITLE
Board type and Port not saved

### ISSUE THREAD

**Issue by djoel1** [arduino/arduino-pro-ide#113]
I've selected board type (NodeMcu V1) and Port and have to input it again when I restart the IDE

**To Reproduce**
Select a board and port
Exit the application
Start the application 
Board and port are not selected

**Desktop 
Windows 7
arduino.Pro.IDE 0.0.2

**Comment by kittaakos** [comment]
We have changed the way we restore the selected board/port between app sessions. I am closing this, for now, let me know if you still experience the problem and I am happy to reopen this task. Thank you!
