### ISSUE TITLE
Confirm Exit not working

### ISSUE THREAD

**Issue by djoel1** [arduino/arduino-pro-ide#114]
Preference Application ConfirmExit   tried always and ifRequired
Push exit, application closes without asking anything

**Expected behavior**
Likley show a message box asking you if you want to exit

**Desktop (please complete the following information):**
 - OS: Windows 7
  IDE 0.0.2

**Comment by mastrolinux** [comment]
This one was a bug in Theia https://github.com/eclipse-theia/theia/blob/aff11bec2a0424a63e506613d9e23f2e6bdd1d42/packages/core/src/browser/window/default-window-service.ts 

Will be fixed when we will rebase to the new master.

**Comment by kittaakos** [comment]
I have updated to `next` (`0.13.0-next.f2b35569`) Theia; I can confirm it works now on macOS. I will re-verify this item before roll out our next release.

**Comment by kittaakos** [comment]
Was fixed in `0.0.3`.
