### ISSUE TITLE
questions about serial plotter.

### ISSUE THREAD

**Issue by breaker123** [arduino/arduino-pro-ide#115]
**Is your feature request related to a problem? Please describe.**
Hi, Awesome work! well done.I have used Arduino for 2 years,I have made many interesting projects.I wanna thank your team with fantastic work.
But ,I also met questions, When I use the serial plotter, I want to extend the display range of the horizontal axis time so that the latest data acquisition and the previous data acquisition can be displayed on the same graph.Second? when the x-coordinate data is a cyclic change in a range, I want the x-coordinate data to be displayed within the range instead of forward.
thanks for your reading.i look forward to your response. my email address is 1701213930@pku.edu.cn , feel free to contact.

**Describe the solution you'd like**
Do a display range adjustable X-axis，Add repeatable options when displaying the same contents.

**Describe alternatives you've considered**

**Additional context**

**Comment by mastrolinux** [comment]
There is no such serial plotter in this IDE. So I am going to close this issue.

**Comment by breaker123** [comment]
Who should I talk to about this problem? Thank you




------------------ 原始邮件 ------------------
发件人: "Luca Cipriani"<notifications@github.com>; 
发送时间: 2019年10月28日(星期一) 晚上8:01
收件人: "arduino/arduino-pro-ide"<arduino-pro-ide@noreply.github.com>; 
抄送: "高伟宝"<894738705@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [arduino/arduino-pro-ide] questions about serial plotter. (#115)




Closed #115.

**Comment by mastrolinux** [comment]
https://github.com/arduino/arduino is the right repo.

**Comment by breaker123** [comment]
thanks for your response



------------------ 原始邮件 ------------------
发件人: "Luca Cipriani"<notifications@github.com>; 
发送时间: 2019年10月28日(星期一) 晚上9:03
收件人: "arduino/arduino-pro-ide"<arduino-pro-ide@noreply.github.com>; 
抄送: "高伟宝"<894738705@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [arduino/arduino-pro-ide] questions about serial plotter. (#115)




https://github.com/arduino/arduino is the right repo.
 
&mdash;
