### ISSUE TITLE
port not able to detect

### ISSUE THREAD

**Issue by Dinakaranevil** [arduino/arduino-pro-ide#120]
i went to the boards manager and ports where not detected

1. just run the Arduino _Ide pro on terminal
2 went to boards for boards selection

**Expected behavior**
ports should be declared

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by per1234** [comment]
Hi @Dinakaranevil. Thanks for taking the time to report this bug.

We have another similar issue report at https://github.com/arduino/arduino-pro-ide/issues/209 that came later, but has more information. It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this one.

If you're still having the same problem after trying out [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4), please comment on https://github.com/arduino/arduino-pro-ide/issues/209 and we'll investigate.
