### ISSUE TITLE
[LS] Cannot fold functions with comments

### ISSUE THREAD

**Issue by naamah75** [arduino/arduino-pro-ide#13]
Cannot fold functions that have comments inside.

The functions is folded only until the comment, then the remaining part of the functions remain unfolded.

![DeepinScreenshot_20191019201605](https://user-images.githubusercontent.com/34965103/67149599-5e7c9e00-f2ad-11e9-8f28-05ab267432cb.png)

![DeepinScreenshot_20191019201612](https://user-images.githubusercontent.com/34965103/67149600-5fadcb00-f2ad-11e9-9dba-07d9df256996.png)

 - OS: Deepin
 - Version 15.11

**Comment by kittaakos** [comment]
Thank you for logging, this is a language server issue.

**Comment by spoenemann** [comment]
The language server does not define any folding. Maybe it's buried in the TextMate grammar, or some default folding of Monaco?

**Comment by kittaakos** [comment]
> language server does not define any folding

I am confused, what do you mean?

[`textDocument/foldingRange`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-14/#textDocument_foldingRange):
 > The folding range request is sent from the client to the server to return all folding ranges found in a given text document.

**Comment by spoenemann** [comment]
Yes, but our current language server doesn't support that request.

**Comment by kittaakos** [comment]
It works now.
