### ISSUE TITLE
Location output files

### ISSUE THREAD

**Issue by HannesBulk** [arduino/arduino-pro-ide#130]
The output files are now places in a random-named temp directory.
In Preferences.text it is possible to change this location to another user defined location.
But this is always the same path, that will be overwritten.
I want to be able to place all output files (hex and listings) in a subfolder of the current project.

This can be easy if there is a Variable i can use, with the full path of the current project, but I cannot find any documentation.

My request is to make it possible put the Hex and Listing files "Output" subdirectory within the project, instead of the random generated temp directory.

**Comment by per1234** [comment]
Hi @HannesBulk. Thanks so much for your excellent suggestion!

This is now supported [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4) via **Sketch > Export Compiled Binary**.
