### ISSUE TITLE
Add close sketch option

### ISSUE THREAD

**Issue by sevsev9** [arduino/arduino-pro-ide#133]
**Is your feature request related to a problem? Please describe.**
There is no proper way to close a sketch or any other window really in the IDE. So it just keeps filling up the window bar until you close the IDE.

**Describe the solution you'd like**
A small "x" on every tab open and the CTRL+W shortcut to close focused tabs fast.

**Describe alternatives you've considered**
Maby also add to context menu of the tabs' header.

Edit: There seems to be an "x" on the top right but it is invisible plus it only exists on the preferences tab (at least in v0.0.2)

**Comment by svenefftinge** [comment]
It is intentionally omitted in the default classic mode, as it is meant to be used on a single sketch that has all its files open. You can switch to advanced mode, where the close option is present (the cross in the tab, see screenshot).

<img width="743" alt="Screenshot 2019-11-28 at 08 35 10" src="https://user-images.githubusercontent.com/372735/69786129-1315b380-11ba-11ea-9a8f-84ebccc82243.png">

**Comment by sevsev9** [comment]
In this case I would recommend though that you would automatically open a sketch(project) in a new window so that it is not as confusing.
