### ISSUE TITLE
Using dark theme at Select Board screen, it is not possible to see the text I write. The font color is white as the background color.

### ISSUE THREAD

**Issue by flaviosg** [arduino/arduino-pro-ide#137]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by jellewie** [comment]
It is really annoying when people just walk in, screen them have a problem, and run away. this bug report is utterly useless the way you have written it right now.

It would now take devs like 10more minutes to figure out what you mean, and it is just not helpful, why even bother if you do it this way?


**PROPER WAY:**

**Describe the bug**
When in the board selection window, the input field text is white and so is the background

**To Reproduce**
1 open en start the IDE pro (arduino.Pro.IDE 0.0.2) and make sure you are using the DARK THEME
2. open board manager and the 'select board' window should appear
3. type something in the boards selection window
4. text and background is white

**Screenshots**
[https://i.imgur.com/I0gBcUt.png](https://i.imgur.com/I0gBcUt.png)

**OS:** Windows 10 Version	10.0.18362 Build 18362
**Version** arduino.Pro.IDE 0.0.2
**Version** arduino-cli.exe Version: 0.6.0 Commit: f99361a

**Comment by kittaakos** [comment]
Fixed and will be available with the next release.

![screencast 2019-11-26 09-15-00](https://user-images.githubusercontent.com/1405703/69611203-9229b100-102d-11ea-9b44-4cc09d53a8d2.gif)
