### ISSUE TITLE
Command list

### ISSUE THREAD

**Issue by EZduinoOfficial** [arduino/arduino-pro-ide#139]
It would be great if there were a list of commands and their proper explanation.

**Comment by kittaakos** [comment]
> list of commands and their proper explanation.

@EZduinoOfficial, can you please elaborate a bit? Do you want to see the available CLI  commands, or which ones do you mean? Thanks!

**Comment by svenefftinge** [comment]
FWIW pressing F1 or CTRL/CMD + P will open the command palette showing all available commands.
