### ISSUE TITLE
Cannot close opened sketches

### ISSUE THREAD

**Issue by naamah75** [arduino/arduino-pro-ide#14]
When a sketch is loaded and displayed on the IDE is impossible to close it.
All the opened sketches remains displayed even if clicked on "close", "close all", "close to te right" or "close others"

**Desktop (please complete the following information):**
 - OS: Deepin
 - Version 15.11

**Comment by kittaakos** [comment]
It has been fixed and will be available with the next release.

**Comment by kittaakos** [comment]
Was fixed in `0.0.3`.
