### ISSUE TITLE
problems installing on windows 7

### ISSUE THREAD

**Issue by GuilhermeMalta** [arduino/arduino-pro-ide#144]
when I download the file in winrar and run the application for installation, an error pops up saying that it is not compatible with the windows version and tells me to tell the vendor if the version is 32 or 64 bit

**Comment by almeidanasc** [comment]
AC

**Comment by mastrolinux** [comment]
Windows 32bit is not supported nor we want to support it in the short term. In addition Windows 7 is obsolete and End of Life. https://support.microsoft.com/en-us/lifecycle/search?alpha=windows%207
