### ISSUE TITLE
No "flavours" section on Select Board dialog

### ISSUE THREAD

**Issue by pirropirro** [arduino/arduino-pro-ide#146]
**Describe the bug**
Inside the `Select Board` dialog, when I choose a board (es. Arduino Mini) I would expect to see the flavours section in order to change boards' custom options. 

**To Reproduce**
- Open the `Select Board` dialog
- Choose a customizable board (es. `Arduino Mini`) 

**Expected behavior**
The flavours section should appear with the selected board options

**Screenshots**
### **Behavior on the `Arduino Web Editor`**

<img width="736" alt="Screenshot 2019-11-22 at 10 13 51" src="https://user-images.githubusercontent.com/24648253/69413634-7ebad500-0d11-11ea-8e28-5df726977453.png">

<hr />

### **Behavior on  the `Arduino Pro IDE`**

<img width="727" alt="Screenshot 2019-11-22 at 10 25 14" src="https://user-images.githubusercontent.com/24648253/69414137-71521a80-0d12-11ea-9697-72de698dddb7.png">

**Desktop (please complete the following information):**
 - OS: any
 - Version any

**Comment by kittaakos** [comment]
> The flavours section should appear with the selected board options

What is `flavours`, can you please specify it?  Does the CLI capable of providing this info?

**Comment by pirropirro** [comment]
Some board (es. 'Arduino Mini') are distributed with the same fqbn (`arduino:avr:mini`) but with some different specifications (as the processor, CPU frequency, etc...) defined as extra fields in the fqbn (`arduino:avr:mini:cpu=atmega168;`).

In the Web IDE (as you can see in the second screenshot) these kinds of differences are defined as 'flavours' and the user can choose the right board.

Fortunately, the CLI has a command (`boardDetails`) where you can retrieve these options but the IDE still not handle them.

**Comment by kittaakos** [comment]
👍 Cool, thanks for explaining! Are you working on this item? Just asking why is it scheduled for the milestone? Did you put it in the milestone on purpose?

**Comment by pirropirro** [comment]
Yup, I'm working on it (I forgot to assign it to myself :sweat_smile:) but I just put it on the backlog and not in the milestone scope.

**Comment by kittaakos** [comment]
Same as #10.
