### ISSUE TITLE
Configure clangd for proper C++ support

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-pro-ide#149]
@spoenemann wrote on Sep 16:

>When opening a C++ file such as HardwareSerial.h, clangd generates a lot of errors because it is not properly configured. Configuration is documented here:
https://github.com/eclipse-theia/theia/tree/master/packages/cpp#getting-accurate-diagnostics

**Comment by spoenemann** [comment]
New cpp package url: https://github.com/eclipse-theia/theia-cpp-extensions/tree/master/packages/cpp

**Comment by spoenemann** [comment]
This issue depends on https://github.com/arduino/arduino-cli/issues/557 (especially https://github.com/arduino/arduino-cli/issues/557#issuecomment-575527706).

**Comment by ubidefeo** [comment]
This should all be fixed in 0.1.4
Closing for now
