### ISSUE TITLE
Variable not marked

### ISSUE THREAD

**Issue by Alexagomesmar65** [arduino/arduino-pro-ide#150]
String type variable is not marked in Dark mode as variable.

Recognizes the release as a variable, but does not mark as it does with "char" or "int" types.

**Comment by svenefftinge** [comment]
Can you elaborate aa bit more on this or share a screenshot. I'm not entirely sure what you mean.

**Comment by Master811129** [comment]
i think he's right true the String class is not colored in dark theme (and also Arduino theme for me)
![image](https://user-images.githubusercontent.com/37829730/72273645-f0dbd600-363f-11ea-8e5a-819bbe18f041.png)
![image](https://user-images.githubusercontent.com/37829730/72273693-0cdf7780-3640-11ea-8fad-43ba786e7bd2.png)

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/285. Even though this one came first, the mention of the  theme could lead to confusion. As Master811129 kindly pointed out, this issue occurs regardless of which theme you're using.
