### ISSUE TITLE
[Theming] Icons in Arduino theme are not aligned

### ISSUE THREAD

**Issue by svenefftinge** [arduino/arduino-pro-ide#153]
The icons in the default arduino theme are not aligned properly. Some of them are hard to see (seem inactive) others are too dark/solid.
Examples:

<img width="111" alt="Screenshot 2019-11-28 at 08 38 40" src="https://user-images.githubusercontent.com/372735/69786420-af3fba80-11ba-11ea-9a76-e3305fa7dec7.png">
<img width="77" alt="Screenshot 2019-11-28 at 08 38 36" src="https://user-images.githubusercontent.com/372735/69786421-af3fba80-11ba-11ea-8397-7544ad0d1a9b.png">
<img width="245" alt="Screenshot 2019-11-28 at 08 41 10" src="https://user-images.githubusercontent.com/372735/69786505-dd24ff00-11ba-11ea-9498-08da27307872.png">
<img width="194" alt="Screenshot 2019-11-28 at 08 40 45" src="https://user-images.githubusercontent.com/372735/69786506-dd24ff00-11ba-11ea-954b-f95a0ab0dca0.png">

**Comment by jbicker** [comment]
This will be fixed with the theia update regarding theming.
