### ISSUE TITLE
Column Mode (Alt+Drag) for Selection

### ISSUE THREAD

**Issue by jamesgohl** [arduino/arduino-pro-ide#161]
A lot of editors these days allow column mode selection by holding ALT down and dragging the mouse over an area of text, this is on VS and Notepad++, it is extremely useful for replacing text.

I would love to see this implemented in the new Arduino IDE :)

**Comment by kittaakos** [comment]
It is supported just as VS Code supports it: https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

![screencast 2019-12-09 09-12-13](https://user-images.githubusercontent.com/1405703/70418795-66162300-1a64-11ea-8c94-cddfd99100e1.gif)


Please reopen if required.

**Comment by jamesgohl** [comment]
> 
> 
> It is supported just as VS Code supports it: https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor
> 
> ![screencast 2019-12-09 09-12-13](https://user-images.githubusercontent.com/1405703/70418795-66162300-1a64-11ea-8c94-cddfd99100e1.gif)
> 
> Please reopen if required.

What you have demonstrated involves multiple clicks and without the ALT + <drag> functionality I wouldn't have know it existed.

Here is what I mean, the selection rect is possible with ALT key held down ...

![NotepadPP](https://user-images.githubusercontent.com/1788271/70424392-403e4d80-1a67-11ea-9296-696d608d9a69.gif)

As you can see this is a very powerful editing feature, allowing copy and paste into this explicit selection rect.

And in Visual Studio Professional ...

![VSalt](https://user-images.githubusercontent.com/1788271/70424466-5d731c00-1a67-11ea-87e4-a9f2d728dc08.gif)

**Comment by kittaakos** [comment]
I linked the doc, please read. You can use Shift+Alt+Selction: https://code.visualstudio.com/docs/editor/codebasics#_column-box-selection

![screencast 2019-12-09 10-40-26](https://user-images.githubusercontent.com/1405703/70424913-703e1e80-1a70-11ea-8f3f-6aba3a7c6348.gif)

**Comment by jamesgohl** [comment]
Ahh ok.  Standard is ALT+Drag across all applications.  

VS Code doesn't have this, but VS Professional does - and many others.
