### ISSUE TITLE
Bug completion

### ISSUE THREAD

**Issue by chipxx** [arduino/arduino-pro-ide#165]
Hi, I'm trying, finally, this version that has the autocompletion, arduino-pro-ide-0.0.3-alpha.preview-windows, but I found that it only works once. Let me explain: I run the program I start to write some commands and he immediately suggests the command. I do it the second time and it doesn't work anymore... Does it happen only to me or is it normal?

**Comment by per1234** [comment]
Duplicate of https://github.com/arduino/arduino-pro-ide/issues/166
