### ISSUE TITLE
how to install on linux - missing dependencies 

### ISSUE THREAD

**Issue by SquallHalle** [arduino/arduino-pro-ide#168]
It would be nice to get an "how to" or required dependencies like clnag and so on.

**Comment by spoenemann** [comment]
Related: #67

**Comment by per1234** [comment]
As mentioned in https://github.com/arduino/arduino-pro-ide/issues/67#issuecomment-611381186, all dependencies should now be bundled with Arduino Pro IDE, so you only need to follow [the simple installation instructions](https://github.com/arduino/arduino-pro-ide#install) are you're ready to go!
