### ISSUE TITLE
Include library no code

### ISSUE THREAD

**Issue by Ferreira31** [arduino/arduino-pro-ide#175]
Nao sei se ja falaram isso, ou se ja tem e nao consegui usar, mas sinto falta de quando clicar em library, ter todas as bibliotecas instaladas no momento, e eu poder simplesmente clicar e ela é adicionada com o #include

**Comment by spoenemann** [comment]
Output of Google Translate:

> I don't know if they already said that, or if they already have and I couldn't use it, but I miss when I click on library, have all the libraries installed at the moment, and I can just click and it is added with #include

**Comment by spoenemann** [comment]
Duplicate of #76
