### ISSUE TITLE
Problem with search board (3rd party --additional-urls)

### ISSUE THREAD

**Issue by Master811129** [arduino/arduino-pro-ide#177]
**Describe the bug**
"Search board"  doesn't search any 3rd party board.

**To Reproduce**
1. Go to 'Select board and port'
2. Click on 'SEARCH BOARD'
3. type a non-official board name WITH " '' CHARACTER
4. See bug

**Screenshots**
![Annotation 2020-01-15 211843](https://user-images.githubusercontent.com/37829730/72460255-b611a380-37e1-11ea-9bf9-69a63789a0d6.png)
![Annotation 2020-01-15 212111](https://user-images.githubusercontent.com/37829730/72460269-bca01b00-37e1-11ea-9a0c-9932b63c907a.png)
![Annotation 2020-01-15 212519](https://user-images.githubusercontent.com/37829730/72460286-c590ec80-37e1-11ea-9133-baeb249e4d3a.png)
![Annotation 2020-01-15 212336](https://user-images.githubusercontent.com/37829730/72460302-ca55a080-37e1-11ea-81d4-9f625201bac9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by Master811129** [comment]
I think the IDE has some problems with "space" character.
Do you have any idea?

**Comment by kittaakos** [comment]
> any 3rd party board.

Can you please share your 3rd party core URL which contains `ESP32 Dev Module`. How did register your 3rd party boards list into the app, did you do it via the CLI manually?

**Comment by kittaakos** [comment]
> 3rd party core URL which contains `ESP32 Dev Module`

I guess this one: https://raw.githubusercontent.com/espressif/arduino-esp32/master/package/package_esp32_index.template.json. At least it contains the `ESP32 Dev Module` board.

**Comment by Master811129** [comment]
> > 3rd party core URL which contains `ESP32 Dev Module`
> 
> I guess this one: https://raw.githubusercontent.com/espressif/arduino-esp32/master/package/package_esp32_index.template.json. At least it contains the `ESP32 Dev Module` board.

I use this 3rd party core
https://dl.espressif.com/dl/package_esp32_index.json

i added this core using JAVA ide.
i'm using 0.0.3 alpha and win10.

**Comment by kittaakos** [comment]
It seems to be a CLI issue. I have opened an upstream ticket: https://github.com/arduino/arduino-cli/issues/569

**Comment by kittaakos** [comment]
This is a missing feature. See my comment here: https://github.com/arduino/arduino-cli/issues/569#issuecomment-580196238

The Pro IDE is not yet fully support 3rd party boards. Let me check how much effort would it take to implement. Bear with me.

**Comment by kittaakos** [comment]
Some progress on this item:

![3rd_party_01](https://user-images.githubusercontent.com/1405703/73673857-ad5d1080-46af-11ea-85c8-32095ffd314b.gif)
![3rd_party_02](https://user-images.githubusercontent.com/1405703/73673858-adf5a700-46af-11ea-8c88-35f6494df83e.gif)
![3rd_party_03](https://user-images.githubusercontent.com/1405703/73673859-adf5a700-46af-11ea-9121-2f7fc1d8c8ad.gif)
![3rd_party_04](https://user-images.githubusercontent.com/1405703/73673861-adf5a700-46af-11ea-9f94-bb480e314ab6.gif)


Please note, it is pretty much in development state and is currently blocked by arduino/arduino-cli#570

**Comment by wcarvalho0** [comment]
> Some progress on this item:
> 
> ![3rd_party_01](https://user-images.githubusercontent.com/1405703/73673857-ad5d1080-46af-11ea-85c8-32095ffd314b.gif)
> ![3rd_party_02](https://user-images.githubusercontent.com/1405703/73673858-adf5a700-46af-11ea-8c88-35f6494df83e.gif)
> ![3rd_party_03](https://user-images.githubusercontent.com/1405703/73673859-adf5a700-46af-11ea-9121-2f7fc1d8c8ad.gif)
> ![3rd_party_04](https://user-images.githubusercontent.com/1405703/73673861-adf5a700-46af-11ea-9f94-bb480e314ab6.gif)
> 
> Please note, it is pretty much in development state and is currently blocked by [arduino/arduino-cli#570](https://github.com/arduino/arduino-cli/issues/570)

on my arduino pro ide it doesn't have this arduino tab from the second image

**Comment by kittaakos** [comment]
> on my arduino pro ide it doesn't have this arduino tab from the second image

We have not released it yet. Work in progress...

Please bear with us.

**Comment by wcarvalho0** [comment]
> > on my arduino pro ide it doesn't have this arduino tab from the second image
> 
> We have not released it yet. Work in progress...
> 
> Please bear with us.

ok thank you very much, do you have any prediction of when it will be released?

**Comment by Master811129** [comment]
This issue has been fixed so i close it

**Comment by Master811129** [comment]
This issue has been fixed so i close it
