### ISSUE TITLE
When the debugger will be released?

### ISSUE THREAD

**Issue by wanggaoteng** [arduino/arduino-pro-ide#178]
Hi, in this blog:
https://blog.arduino.cc/2019/10/25/new-arduino-pro-ide-a-closer-look/
it says that:
-------------------------------------------------------------------------------
> Debugger coming soon!
Set breakpoints, view trace, step through execution and much more
Debug your application without affecting timing with a Serial.print()
-------------------------------------------------------------------------------
When this debugger will be released? And can it support arduino uno or mega2560?

Best regards.

**Comment by spoenemann** [comment]
Hi! A first preview of the debugger will be included in version 0.0.5 (probably beginning / mid February).

The preview version will not support all boards, but I can't provide a compatibility list yet.

**Comment by Master811129** [comment]
> Hi! A first preview of the debugger will be included in version 0.0.5 (probably beginning / mid February).
> 
> The preview version will not support all boards, but I can't provide a compatibility list yet.

and when the 0.0.4 version will be released?

**Comment by spoenemann** [comment]
As soon as possible. It's currently blocked by #179.

**Comment by gmacario** [comment]
According to the release notes, v0.0.5-alpha (released today) includes debugger support for SAMD boards: https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.5-alpha.preview
