### ISSUE TITLE
[linux] Unable to start debug session - Error "this.gdbServer.off is not a function"

### ISSUE THREAD

**Issue by aentinger** [arduino/arduino-pro-ide#182]
**Describe the bug**
When attempting to start the debugger the error message "this.gdbServer.off is not a function" appears.

**To Reproduce**
1. Switch to Advanced Mode
2. Create a simple test sketch
3. Compile and download to board to verify programming and downloading works (and view output in serial monitor)
4. Press **Debug -> Start Debugging**.

**Expected behavior**
I would have expected to be launched into some kind of debugging mode where I can single-step the program.

**Screenshots**
The error message is visible in the lower / right corner of the IDE. No output on the console used to launch the Pro IDE.
![2020-01-21-Failed-To-Launch-Debugger](https://user-images.githubusercontent.com/3931733/72807927-ba621480-3c58-11ea-8a18-370071ce5149.png)

**Debug Console Output**
```
Info : CMSIS-DAP: FW Version = 02.01.0157
Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 1 nTRST = 0 nRESET = 1
Info : CMSIS-DAP: Interface ready
Info : clock speed 400 kHz
Info : SWD DPIDR 0x0bc11477
Info : at91samd21g18.cpu: hardware has 4 breakpoints, 2 watchpoints
Info : Listening on port 50000 for gdb connections
Info : accepting 'gdb' connection on tcp/50000
Info : SAMD MCU: SAMD21G18A (256KB Flash, 32KB RAM)
undefined debug reason 7 - target needs reset
0x0000060c in ?? ()
target halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x0000060c msp: 0x20007ffc
target halted due to debug-request, current mode: Thread 
xPSR: 0x61000000 pc: 0x0000060c msp: 0x20007ffc
Attached to debugger on port 50000
```
**Desktop (please complete the following information):**
 - OS: `Ubuntu 18.04.3 LTS`
 - Pro IDE: `Arduino Pro IDE-0.0.4-3e8c609-linux`

**Additional Information**
- Debugger: `Black Magic Probe V2.0`
- Target Board: `Arduino Zero`

**Comment by spoenemann** [comment]
Solved.

**Comment by aentinger** [comment]
I can confirm that debugging works now for **Arduino Pro IDE-0.0.4-dd0b9bf-linux** :+1:
