### ISSUE TITLE
Change application settings directory

### ISSUE THREAD

**Issue by spoenemann** [arduino/arduino-pro-ide#184]
Arduino Pro IDE stores its settings (`recentworkspace.json`, `settings.json`) in the default location of Theia, which is `$HOME/.theia`. The consequence is that it shares these settings with other Theia-based applications. We should move at least part of these settings to a dedicated directory. For example, it does not make sense to share the recent workspaces with other applications.

**Comment by akosyakov** [comment]
It would help if https://github.com/eclipse-theia/theia/pull/6650 is landed.

**Comment by kittaakos** [comment]
This is done. Waiting for the review.

For the record, the Pro IDE will store the settings under the `~/.arduinoProIDE/` location.

**Comment by spoenemann** [comment]
See https://github.com/eclipse-theia/theia/issues/7218.

**Comment by kittaakos** [comment]
> See [eclipse-theia/theia#7218](https://github.com/eclipse-theia/theia/issues/7218).

@spoenemann, see what? What's missing from here?

**Comment by spoenemann** [comment]
I just wanted to link that issue as it is related.
