### ISSUE TITLE
Make debugger available for other boards

### ISSUE THREAD

**Issue by spoenemann** [arduino/arduino-pro-ide#185]
The current debugger is hard-coded to work only for Arduino Zero. It should be generalized by automatically resolving the required debugging tools (`gdb`, `objdump`, `openocd`), preferably through the arduino-cli.

**Comment by mastrolinux** [comment]
please open a bug at https://github.com/arduino/arduino-cli and link this one.

**Comment by spoenemann** [comment]
Fixed in v0.0.5
