### ISSUE TITLE
Toggling Advanced Mode deletes Code

### ISSUE THREAD

**Issue by soundstorm** [arduino/arduino-pro-ide#192]
* I just opened 0.0.4 on my Mac, which loaded the first sketch (1) it found in the home directory.
* Opened another file (2) from a subdirectory via Open Icon -> Open... in a new window
* Toggled Advanced Mode in (2) -> On
* Arduino replaces (2) by (1) and now shows two windows with sketch (1)
* Opening (2) via Browse... shows now an empty sketch.

#110 relevant?

**Comment by spoenemann** [comment]
I submitted a fix for the "Open..." dialog, available in v0.0.6.

@soundstorm are you sure any code was deleted? That should not happen, and I was not able to reproduce it.

**Comment by ubidefeo** [comment]
@spoenemann @soundstorm 
this might be related to #212

**Comment by kittaakos** [comment]
The fix is available from the 0.0.6 release.
