### ISSUE TITLE
Analog sensor doesn't print new value to Serial Monitor each loop

### ISSUE THREAD

**Issue by remotesense** [arduino/arduino-pro-ide#197]
**Describe the bug**

Using V0.0.4
I am using an MKR 1010 board and I have a potentiometer on A03
I have varified that my code works fine on normal Arduino IDE serial monitor and directly copied it over into Pro.  It prints the current value of the sensor but does not update it when I adjust the sensor Serial Monitor just stays stuck on the same value.  I need to then re-load the Serial Monitor to get a new value.

**To Reproduce**
1. Use a generic script that reads an analog Pin and prints the value to serial monitor
Use an analog sensor like POT that can update manually
2. Click on Serial Monitor, even if its in Autoscroll mode, none of the sensor information updates.

**Expected behavior**
I expected that it would print a new value based on sensor position each loop as I have varified the code does in the old Arduino IDE.

**Screenshots**

EDIT: I pasted the wrong screenshot before that was unrelated to this bug issue; I have again re-tested on an arduino DUE on A0 and reproduced the issue with the code bellow.
![image](https://user-images.githubusercontent.com/13763531/75317417-b195db80-58b3-11ea-94ae-acb74d0e4eb6.png)

![image](https://user-images.githubusercontent.com/13763531/73592139-c7c5ab80-4542-11ea-9f81-4429b1e74d7b.png)

**Desktop (please complete the following information):**
 - OS: Windows 10

**Comment by owennewo** [comment]
@remotesense - you forgot the `Serial.begin(9600);` in `void setup()`

**Comment by remotesense** [comment]
> @remotesense - you forgot the `Serial.begin(9600);` in `void setup()`
> 
> also I think you want
> `Serial.println(sensorValue);`
> 
> you are printing sensorPin

My Bad, wrong screencap; it was not the code that I tested, the code that I tested did have a baud rate of 9600 and was printing multiple sensor values.  As stated in the comment, it was fully tested and working in normal Arduino IDE... 

Thanks,

Tim

**Comment by per1234** [comment]
@remotesense if you change the delay to 100, does the problem go away?

I can reproduce the issue, and also your findings that it does not occur with the original IDE's Serial Monitor. I think what happens is the Arduino Pro IDE's Serial Monitor is too slow to keep up with the data. What you're seeing is it working its way though the backlog of output. So there is just an ever increasing lag before the effects of a change in voltage on `A0` are shown

**Comment by kittaakos** [comment]
Was fixed via https://github.com/arduino/arduino-pro-ide/issues/197
