### ISSUE TITLE
Dark mode options

### ISSUE THREAD

**Issue by remotesense** [arduino/arduino-pro-ide#199]
In the original Arduino IDE I have a custom theme installed.
It would be nice to see a dark option that has the dark blue-grey tone and nicely contrasted text in a similar style to this one.
See picture as example:
![image](https://user-images.githubusercontent.com/13763531/73593280-0876f200-454e-11ea-99f0-a5afc546c8d3.png)
Comparison to current Dark Mode
![image](https://user-images.githubusercontent.com/13763531/73593445-2f362800-4550-11ea-907c-750af7c37513.png)

While its low priority, I find the colors of this theme relaxing on the eyes, moreso than the current dark mode, although it is already a lot nicer than the white alternative.
You can find the original theme for reference here.  It is modeled after VSCode theme "One Dark Pro"

https://create.arduino.cc/projecthub/konradhtc/one-dark-arduino-modern-dark-theme-for-arduino-ide-2fca81

**Comment by kittaakos** [comment]
Good idea; with the next version we want to support any VS Code themes.

![Screen Shot 2020-04-02 at 19 28 26](https://user-images.githubusercontent.com/1405703/78279800-5f7e5080-7518-11ea-97a0-da451aa65982.jpg)


----

![screencast 2020-04-02 19-25-18](https://user-images.githubusercontent.com/1405703/78279784-57261580-7518-11ea-8f7b-af8b1bd150b1.gif)

**Comment by ubidefeo** [comment]
brought this one into #58
