### ISSUE TITLE
Serial Monitor only shows the incoming data after it receives '\n' character

### ISSUE THREAD

**Issue by Master811129** [arduino/arduino-pro-ide#201]
**Describe the bug**
Serial Monitor only shows the incoming data after it receives '\n' character

**To Reproduce**
1. Go to 'Arduino Pro IDE v0.0.4'
2. upload this sketch:
```cpp
void setup()
{
    Serial.begin(9600);
}

void loop()
{
    for (uint8_t a=0; a<12; a++)
    {
        Serial.print("hello world!");
        delay(1000);
    }
    Serial.write('\n');//if you comment this line you CANNOT see anything in serial monitor
}

```
3. comment Serial.write('\n');
4. re-upload the sketch
5. See the problem

**Desktop (please complete the following information):**
 - OS: Win 10

if you comment Serial.write('\n'); line you CANNOT see anything in serial monitor

**Comment by kittaakos** [comment]
Fixed. Thank you for the steps and the snippet, @Master811129!

![screencast 2020-03-02 14-48-52](https://user-images.githubusercontent.com/1405703/75682126-33f81400-5c95-11ea-8988-d534a988880d.gif)

**Comment by Master811129** [comment]
> Fixed. Thank you for the steps and the snippet, @Master811129!
> 
> ![screencast 2020-03-02 14-48-52](https://user-images.githubusercontent.com/1405703/75682126-33f81400-5c95-11ea-8988-d534a988880d.gif)

thanks man.
when can we see 0.0.6

**Comment by kittaakos** [comment]
> thanks man.

Thank you for your detailed bug/feature reports.

> when can we see 0.0.6?

I cannot say it for sure; we target the end of March. The release is planned to be shipped with 3rd part boards package (core) support via the Arduino CLI configuration. Plus we want to include full 3rd party, board-specific core settings (#10.)
