### ISSUE TITLE
"Comment / Uncomment" option

### ISSUE THREAD

**Issue by OslafEman** [arduino/arduino-pro-ide#206]
**Is your feature request related to a problem? Please describe.**
Using the original IDE I loved the option "Comment / Uncomment" available with the secondary mouse click.  

**Describe the solution you'd like**
Could be very nice to see it implemented in the new Pro IDE.

**Comment by owennewo** [comment]
@OslafEman - just to clarify you want to see that in the right click menu?

You can use the shortcut <ctrl> <forward-slash> (i.e. <ctrl>/) both pressed together.  This is a standard shortkey on most IDEs so worth learning.  This works on multiple lines too.

**Comment by OslafEman** [comment]
Thanks a lot @owennewo, I didn't know that.  As I did not understand your shortcut  (i.e. /), I searched for the usual shortcuts and found the Ctrl K - Ctrl C for comments and Ctrl K - Ctrl U for uncomment.  They work great.

**Comment by spoenemann** [comment]
You can press `F1` and then enter parts of a command name (e.g. _comment_) to see the keyboard shortcuts for your operating system / keyboard layout. For example, the _"Toggle Line Comment"_ command is very useful, but its shortcut is quite different on every keyboard layout.
