### ISSUE TITLE
Randomly a tab kidnaps focus while not selected

### ISSUE THREAD

**Issue by ubidefeo** [arduino/arduino-pro-ide#212]
**Describe the bug**
I had a project with several files. Everything worked fine until I toggled Advanced Mode off.
At this point the focus was captured by my last open tab.
The problem presents as impossibility to type or modify text in the currently open tab, which is solved by switching to Advanced Mode.
After a while I switched to all the other tabs one by one and ended up on the last one which at that point contained all the text I had typed while trying to regain access to what I thought was a faulty keyboard.

**To Reproduce**
- have project with multiple tabs/files
- start in Basic Mode
- switch between tabs and type text
- switch to Advanced Mode
- go to any tab
- select some text 
- while selection is active switch to Basic Mode
- the tab's text will still be selected
- leave the selection active and start moving across tabs and type/modify text
- sometimes the text will be correctly edited, but some other times the text will be actively changed in other tabs not visible at the moment, racking havok on your source code

**Expected behavior**
n/a

**Screenshots**
see screen capture at the link in next comment

**Desktop (please complete the following information):**
 - OS: MacOS
 - 10.14.6 (Mojave)

**Additional context**
n/a

**Comment by ubidefeo** [comment]
I have been messing with it a bit further and it's worse than I thought.
Again, it only happens in basic mode.
See capture video below
https://drive.google.com/file/d/1Z1pU2X30JRqRSq0oape6wi_FBiks8y3T/view?usp=sharing

**Comment by ubidefeo** [comment]
Of course when going back to the tabs where text has been edited, no UNDO is available and the file appears to have been automatically saved.
This means your code is lost forever.

**Comment by spoenemann** [comment]
Could this be related to https://github.com/eclipse-theia/theia/issues/6298 ?
