### ISSUE TITLE
Problem with high contrast theme: icons in top-left are invisible.

### ISSUE THREAD

**Issue by Master811129** [arduino/arduino-pro-ide#218]
**Describe the bug**
icons in top-left are invisible.

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Color Theme'
3. Click on 'High Contrast (Theia)'

**Screenshots**
![Annotation 2020-02-27 131927](https://user-images.githubusercontent.com/37829730/75558343-f0b06200-5a56-11ea-9ad3-b58ae89e96ac.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 -Arduino version: 0.0.5 alpha

**Comment by kittaakos** [comment]
This has been fixed.

![screencast 2020-04-28 11-47-03](https://user-images.githubusercontent.com/1405703/80473312-42d20e80-8946-11ea-9ee5-ac0b7eeca5e5.gif)

**Comment by Master811129** [comment]
> This has been fixed.
> 
> ![screencast 2020-04-28 11-47-03](https://user-images.githubusercontent.com/1405703/80473312-42d20e80-8946-11ea-9ee5-ac0b7eeca5e5.gif)

cool can we see the fix in 0.0.5?

**Comment by Master811129** [comment]
![image](http://uupload.ir/files/ei3l_bug.bmp)

in 0.0.6 still icons in top-left are invisible.

**Comment by kittaakos** [comment]
> in 0.0.6 still icons in top-left are invisible.

I know. It did not make it to the 0.0.6, sorry. The fix is already on our `master`, though.
