### ISSUE TITLE
Please add a multi cursor selection, similar to what we see on Sublime Text.

### ISSUE THREAD

**Issue by RaiyaanAbdullah** [arduino/arduino-pro-ide#220]
While using Arduino, we sometimes have to edit the same thing on multiple lines. If we could press Ctrl+Left Mouseclick to place multiple cursors on multiple lines and edit them all at once, it would boost efficiency. Text editors like Sublime text already have this feature.

**Comment by Master811129** [comment]
> While using Arduino, we sometimes have to edit the same thing on multiple lines. If we could press Ctrl+Left Mouseclick to place multiple cursors on multiple lines and edit them all at once, it would boost efficiency. Text editors like Sublime text already have this feature.

You can use alt + left mouse click

**Comment by RaiyaanAbdullah** [comment]
Thanks.

**Comment by Master811129** [comment]
> Thanks.

Anytime 😉
