### ISSUE TITLE
avrdude: stk500_recv(): programmer is not responding avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

### ISSUE THREAD

**Issue by StipeElektrotechnik** [arduino/arduino-pro-ide#221]
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 1 of 10: not in sync: resp=0x00

I gonna use the Arduino Nano with the old boot loader how I switch in the new Arduino Pro IDE the bootoader

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/10
