### ISSUE TITLE
Additional Boards

### ISSUE THREAD

**Issue by caiossoliveira** [arduino/arduino-pro-ide#223]
Version: arduino-pro-ide-0.0.5 - MacOS

Hi! I would like to know if it is possible to add additional boards with JSON URL on this version of Arduino Pro IDE. (Ex: https://arduino.esp8266.com/stable/package_esp8266com_index.json). 
If yes, how could I?

**Comment by per1234** [comment]
Closing as duplicate of https://github.com/arduino/arduino-pro-ide/issues/103
