### ISSUE TITLE
Won't Run On Windows 10 (version 1909 Build 18363.657)

### ISSUE THREAD

**Issue by umerao** [arduino/arduino-pro-ide#227]
**Describe the bug**
I have tried to run Arduino Pro IDE 0.0.5 Alpha.Windows but it shows a error that "This app can't run on your PC- to find a version for you PC, check the software publisher."

I have successfully run the same Arduino pro IDE version on windows 10 version 171...

Please tell me that how to encounter that?

 - OS: [Windows 10]
 - Version [1909 Build 18363.657]

**Comment by kittaakos** [comment]
@umerao, we only support and want to support 64bit architectures as of now.

See: https://github.com/arduino/arduino-pro-ide/issues/138
