### ISSUE TITLE
Board search should be fuzzy

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-pro-ide#232]
Searching for `ar du` in the _Board Select_ should return with result `Arduino Duemilanove or Diecimila`. Current behavior: no match.

**Comment by kittaakos** [comment]
It will be available as an experimental feature in  0.0.6.

**Comment by noob-master147** [comment]
Hey, @kittaakos 
I would like to work on this bug

**Comment by kittaakos** [comment]
Thank you for your interest, @noob-master147. Unfortunately, the Pro IDE code is not open-sourced yet 😕

And we have this new feature kind of available from the next release:

![Screen Shot 2020-04-03 at 11 45 36](https://user-images.githubusercontent.com/1405703/78347402-bc254e00-75a0-11ea-92cc-5b2507c85f0b.jpg)

Did you know; the [Arduino CLI](https://github.com/arduino/arduino-cli) powers the Pro IDE. The CLI code is open source, if you want to  contribute there, the is an open feature request for the fuzzy search: https://github.com/arduino/arduino-cli/issues/629

You will need some golang knowledge ;)

**Comment by noob-master147** [comment]
thanks @kittaakos 
i will surely check that out

**Comment by kittaakos** [comment]
Now it works even with whitespces.

![Screen Shot 2020-04-28 at 16 18 07](https://user-images.githubusercontent.com/1405703/80498413-fb5e7900-896b-11ea-9110-42b6da220f44.jpg)

**Comment by Master811129** [comment]
> Now it works even with whitespces.
> 
> ![Screen Shot 2020-04-28 at 16 18 07](https://user-images.githubusercontent.com/1405703/80498413-fb5e7900-896b-11ea-9110-42b6da220f44.jpg)

nice!
does it also search 3rd party cores?

**Comment by kittaakos** [comment]
Sure.

![Screen Shot 2020-04-29 at 10 58 45](https://user-images.githubusercontent.com/1405703/80578300-88571000-8a08-11ea-9330-df8a5fbdd0bb.jpg)

PS: I will ask around what's holding back the release.
