### ISSUE TITLE
On screen debugger

### ISSUE THREAD

**Issue by RoyHopkins** [arduino/arduino-pro-ide#235]
Can you or it would be good to be able to run debug on the compiled code without uploading the code to a board.

**Comment by tuxedo0801** [comment]
that would require to emulate the microcontroller on you PC. How will you then handle the IO pins of your arduino?
Buy an Atmel ICE debugger, connect it to your SWD-capable Arduino Board an debug in the final hardware. That already works and you're sure the behavior of your code is working as expected on your final hardware.

**Comment by ubidefeo** [comment]
@RoyHopkins , this is unfortunately out of scope.
I wish such thing would be possible without losing anyone in the field 😄 
Will close
