### ISSUE TITLE
Standard Libraries unavailable

### ISSUE THREAD

**Issue by Oldman1066** [arduino/arduino-pro-ide#238]
**Describe the bug**
Importing standard libraries is impossible. When the library manager comes up the standard libraries are not there i.e. standard Servo so that basic servo function can be used Servo.h so that Servo myservo can be used.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 Windows 10

**Additional context**

**Comment by per1234** [comment]
>When the library manager comes up the standard libraries are not there i.e. standard Servo

Are you saying that you can't find the Servo library listed in Library Manager? Or are you saying that you are expecting the Servo library to be pre-installed?

![Clipboard01](https://user-images.githubusercontent.com/8572152/78254720-2a87e480-74ab-11ea-90cf-c93b5b491d75.png)

**Comment by Oldman1066** [comment]
So sorry I missed that one completely.
Than you so much.
