### ISSUE TITLE
Anyone know how to add the ESP8266 boards in PRO IDE

### ISSUE THREAD

**Issue by mikeboski** [arduino/arduino-pro-ide#239]
I know how to do it in the standard Arduino IDE.
Thanks for any help this software looks awesome.

**Comment by kittaakos** [comment]
This feature will be available with the next release, I am still working on the finalization. See: #177 and #215.

**Comment by mikeboski** [comment]
You are awesome

**Comment by Hennadii65** [comment]
It is advisable to add the Developer board Robotdyn Mega2560+ESP8266. Best regards!

**Comment by mikeboski** [comment]
And that will let me use the Wemos ESP12 D1 boards?
Thanks for your help.
How do I add boards I couldn't figure it out. 
Thanks for your time and kindness

**Comment by Master811129** [comment]
> This feature will be available with the next release, I am still working on the finalization. See: #177 and #215.

we can't wait

**Comment by brandanop** [comment]
You have to fo to File... Settings... Open CLI Configuration... and then update the config to add the new board link as shown:

board_manager:
  additional_urls: [### http://arduino.esp8266.com/stable/package_esp8266com_index.json]

**Comment by kittaakos** [comment]
I have created and pinned and issue describing the CLI config a with a bit more details: https://github.com/arduino/arduino-pro-ide/issues/245
