### ISSUE TITLE
Outline view functions listed twice, variables ok 

### ISSUE THREAD

**Issue by hex705** [arduino/arduino-pro-ide#24]
**Describe the bug**
Outline view (nice!) lists variables individually but functions (built in and custom)  are listed twice. 

**To Reproduce**
Open an Arduino file.
Open Outline view on right.
Functions are listed twice.

**Expected behavior**
Functions should be listed once.

**Desktop (please complete the following information):**
Mac OSX 10.13.6
High Sierra

**Comment by mastrolinux** [comment]
Confirmed, I tested it with the SAMD core.

**Comment by 32leaves** [comment]
fixed in https://github.com/bcmi-labs/arduino-language-server/pull/12

**Comment by kittaakos** [comment]
Was fixed in `0.0.3`.
