### ISSUE TITLE
library manager

### ISSUE THREAD

**Issue by mspcbs** [arduino/arduino-pro-ide#247]
Library manager shows the minimum libraries index.

**Comment by kittaakos** [comment]
> Library manager shows the minimum libraries index.

Please explain this. If I remember correctly, there should be a bug-report template for the issues; what is the expected behavior, what did you try, etc?

**Comment by per1234** [comment]
Closing due to lack of feedback. @mspcbs if you'll comment here with the requested information I'll be happy to reopen this.
