### ISSUE TITLE
Tools

### ISSUE THREAD

**Issue by mspcbs** [arduino/arduino-pro-ide#248]
tools ->serial monitor is ended after nothing is shows like use bootloader and etc.

**Comment by kittaakos** [comment]
> is ended after nothing is shows like use bootloader and etc.

Can you please explain this bug-report a little bit more?

**Comment by per1234** [comment]
Closing due to lack of feedback. @mspcbs if you will comment here with a detailed set of steps that would allow us to reproduce the issue, then I'll be happy to reopen.
