### ISSUE TITLE
Board Manager & Library Extensions

### ISSUE THREAD

**Issue by jojobudiman** [arduino/arduino-pro-ide#25]
This is a feature request but I would love to this IDE could support more extensions, user-friendly and somehow support GitLens such as VSCode. Live share is a good option for monitoring and teaching people who are new to the IDE. File icons and fonts would be appreciated so we could develop in the IDE comfortably. Because this is just an alpha version, there's still a long way to go. Just giving good luck to the Arduino team and if the team could implement these features I mentioned for the IDE. It would be great! 😊

Don't forget to fix the user interface font, add keyboard shortcuts and simplify the library description (would be nice if there were library icons 😃)
![image](https://user-images.githubusercontent.com/24372255/67155182-62073800-f334-11e9-969f-e698fd7ed7c2.png)

**Comment by spoenemann** [comment]
> fix the user interface font

What's wrong with the font?

> add keyboard shortcuts

Done: #17

> simplify the library description (would be nice if there were library icons 😃)

Related: #21

**Comment by jojobudiman** [comment]
> What's wrong with the font?
Only the board manager font though if it's unnecessary 🤔

I'll close the issue since enhancements were made.
