### ISSUE TITLE
Could not start editor support.<br>Error during build: exec: "/bin/avr-g++": file does not exist<br>

### ISSUE THREAD

**Issue by Denontime** [arduino/arduino-pro-ide#254]
**Describe the bug**
when use v-0.6 on windows ,it put this ,and I can't use it
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by LumitoLuma** [comment]
@Denontime I also have this problem. I have temporary solved it (on my local computer) with this steps:

1.  Go to boards manager.
2.  Install the previous version of the board you have selected.
3.  Then, uninstall the version you have recently downloaded.
4.  Finally, install the latest version of the board.

Hope it solves your problem!

**Comment by ubidefeo** [comment]
This issue can happen when the CLI fails to complete installation of a core and its tools.
It is a sporadic issue and we now have a Knowledge-Base article to address it.
https://support.arduino.cc/hc/en-us/articles/360018444739-Error-file-does-not-exist-no-such-file-or-directory-system-cannot-find-the-file-specified
This issue will hence be closed for now.
Please also test with the latest release, but it might be that you never bump into it again
