### ISSUE TITLE
CLI configs do not work on Windows

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-pro-ide#255]
@csaba911 wrote [here](https://github.com/arduino/arduino-pro-ide/issues/245#issuecomment-626036326):

> Awesome tutorial, much more detailed what is needed but my clean fresh install of 0.0.6 works nothing like illustrated.
> when searching for board -> not found, I mean
> ![SharedScreenshot](https://user-images.githubusercontent.com/17306541/81444737-df5d9300-9134-11ea-8e18-9df596e19666.jpg)

**Comment by kittaakos** [comment]
> clean fresh install of 0.0.6 works nothing like illustrated.

@csaba911, I could not reproduce it with the 0.0.6-alpha on Windows. Please try to start the application from a `CMD.exe`.
 - Download the ZIP and unpack,
 - `cd` to `"Arduino Pro IDE-v0.0.6-win"`,
 - start with `"Arduino Pro IDE.exe`".

Do you see any errors in the terminal? What does the status bar show, do it have a yellow (`offline`) background color? Also, please check if it isn't a [port issue on Windows](https://github.com/arduino/arduino-pro-ide/issues/134#issuecomment-553537737), please try to change the `daemon.port` config value.

**Comment by per1234** [comment]
Closing due to lack of feedback. @csaba911 if you are still experiencing this issue when using [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4), and you can comment here with all the information kittaakos requested, we'll investigate further.
