### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by atif85377** [arduino/arduino-pro-ide#256]
I am getting error while compiling the program the error is as reported here:

"Error: Request compile failed with message: 2 UNKNOWN: exit status 1
"
Screenshot of the error is linked below...
![Untitled](https://user-images.githubusercontent.com/60704724/82406470-270ee380-9a80-11ea-8e44-f5e8fb239c46.png)

**Comment by atif85377** [comment]
Please help!!!

**Comment by ubidefeo** [comment]
@atif85377 
please read the errors
this is the repository for this project, not the support forum for Arduino
the error you received is clearly reported in the message:
`1293_test.ino:5:1` 
which means line 5 character 1
`expected ; before }`
you forgot to end your statement.
you can see in the code window that you have a `}` symbol marked with a red underline.

questions and issues with the code are to be posted to the forum in the beginner section.
thank you
ubi

**Comment by atif85377** [comment]
It works.
Thanks for assistance.
