### ISSUE TITLE
No syntax highlighting and intellisense for *.h and *.cpp files

### ISSUE THREAD

**Issue by theelims** [arduino/arduino-pro-ide#257]
**Describe the bug**
There is no syntax highlighting and intellisense support for *.h and *.cpp files. Highlighting works fine for *.ino, however.

**To Reproduce**
Open any *.h or *.cpp file of your liking. 

**Expected behavior**
Other source files should be recognized and treated as source files by the editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/46279009/82484382-25720980-9ada-11ea-8077-b883d6d092d0.png)

**Desktop:**
 - OS: Windows 10 Version 1809
 - Version: 0.0.6 alpha

**Comment by dejanmeznarc** [comment]
I have same issue.

**Comment by THATDONFC** [comment]
I am experiencing the same thing

**Comment by bustix** [comment]
Hi,

I'm experiencing the same issue unfortunately.

**Comment by billsonualberta** [comment]
Same Issue Here.

I'm running MacOs Catalina (10.15.3)

**Comment by Toem5** [comment]
Same issue in linux version (running Linux Mint 18.3)

**Comment by jalius** [comment]
Hi. I'm wondering if we can make a temporary workaround using the _settings.json_ of the .arduinoProIDE.
I see that we can add a preference for file associations: 
```
{
"files.associations": {"*.h":"Cpp", "*.ino":"INO"}
}
```
Is there any way to add the arduino syntax highlighting to .h and .cpp files using this? The value _Cpp_ or _Ino_ doesn't work for the language option and I can't seem to figure it out by any guesswork. It would be so helpful for using the IDE.
