### ISSUE TITLE
Duplicate folder in %APPDATA% on Windows system

### ISSUE THREAD

**Issue by Gabyfle** [arduino/arduino-pro-ide#265]
**Describe the bug**
Arduino Pro IDE is creating a duplicate folder in my AppData directory.

**To Reproduce**
1. Just install Arduino Pro IDE
2. Then use it a little while
3. Go to %APPDATA%/Roaming
4. See the duplicate folders

**Expected behavior**
I can guess this is not an expected behavior. There should be only one folder that contains everything.

**Screenshots**

* `%APPDATA%/Roaming`:

![appdata](https://user-images.githubusercontent.com/18049206/83948924-0cc75a80-a821-11ea-8b5c-971d4014643a.png)

* `%APPDATA%/Roaming/Arduino Pro IDE`:

![first_folder](https://user-images.githubusercontent.com/18049206/83948959-50ba5f80-a821-11ea-8603-06dd8d706bff.png)

* `%APPDATA%/Roaming/arduino-pro-ide`:

![second_folder](https://user-images.githubusercontent.com/18049206/83948984-78112c80-a821-11ea-9421-c913213be6c3.png)

**Desktop:**
 - OS: Windows 10 Family
 - Version	10.0.19041 number 19041

**Comment by ubidefeo** [comment]
@Gabyfle 
these folders are required by Electron to keep some application state info.
We have been looking into ways to move them elsewhere but they are required, hence if they're not here they will be somewhere else on your system.
As we are cleaning up the backlog I will close this issue for now.
Please let us know if this is something that really bothers you to the point of calling it an issue.
We'd have to go through hoops and bars to even research how to change such behaviour.
Hope you'll understand 🙏🏼
