### ISSUE TITLE
Global Shortcut Interference (MacOS 10.15.5): While Arduino Pro IDE Open, Cmd-R Does not Work Globally

### ISSUE THREAD

**Issue by Aks0121** [arduino/arduino-pro-ide#275]
**Describe the bug**
While Arduino Pro IDE is open, Cmd-R ("refreshing" shortcut) does not work in any relevant application (Safari, Chrome, Firefox, etc.). 

**To Reproduce**
1. Launch 'Arduino Pro IDE'
2. Launch 'Safari' or 'Chrome'
3. Try to refresh a page using Cmd-R in either 'Safari' or 'Chrome'
4. Encounter the issue

**Expected behavior**
While manual clicking on the "refresh" button in either relevant application refreshes the page, Cmd-R does not do its intended action. 

**Desktop (please complete the following information):**
 - OS: OS X
 - Version 10.15.5

**Comment by kittaakos** [comment]
Same as https://github.com/arduino/arduino-pro-ide/issues/249.
Here is a workaround you can apply locally: https://github.com/arduino/arduino-pro-ide/issues/249#issuecomment-628531565
