### ISSUE TITLE
Auto Format (Ctrl+T) for Pro IDE

### ISSUE THREAD

**Issue by Aks0121** [arduino/arduino-pro-ide#276]
**Is your feature request related to a problem? Please describe.**
This requested feature is similar to the Auto Format (Ctrl+T) feature in the "regular" Arduino IDE—it properly formats (proper indentation mostly) the script onto which the feature is called. 

**Describe the solution you'd like**
Ideally, I would love to have a similar feature in the Pro IDE.

**Comment by kittaakos** [comment]
You can do it, the keybindings are different, however.

1. You can do it either from the context menu
![Screen Shot 2020-06-19 at 09 04 48](https://user-images.githubusercontent.com/1405703/85106391-6ad64380-b20c-11ea-81d2-4cf567593c2d.jpg)
 of the editor:

2. Or you can use the [standard keychord from VS Code](https://code.visualstudio.com/docs/getstarted/keybindings#_keyboard-rules): <kbd>Ctrl/⌘</kbd>+<kbd>K</kbd>, then <kbd>Ctrl/⌘</kbd>+<kbd>F</kbd>.

![screencast 2020-06-19 09-05-12](https://user-images.githubusercontent.com/1405703/85106614-c7396300-b20c-11ea-9876-35f19dcca2d9.gif)

I hope this helps.
