### ISSUE TITLE
Can't close tabs 

### ISSUE THREAD

**Issue by Luco1092** [arduino/arduino-pro-ide#280]
hi, i have this problem, maybe you can help me:
Once i have opened a tab this can't be closed, there is a way to do it?
in my case i dont have the buttons to close the tabs so now i have a lot and unnecesary tabs opened, doing anticlick shows an empty box

![image](https://user-images.githubusercontent.com/67332054/85426290-e3f0d600-b53f-11ea-8b26-378bc6de8b23.png)

![image](https://user-images.githubusercontent.com/67332054/85426726-77c2a200-b540-11ea-903a-cf31847db55c.png)

 - OS: w10
 - im using the last version of the IDE 0.0.6

thank you, this is an excellent proyect.

**Comment by Attigliuzzo** [comment]
Enable the advanced mode in the help menu.

**Comment by Luco1092** [comment]
thank you
