### ISSUE TITLE
Only .ino files have code highlight and intellisense, etc.

### ISSUE THREAD

**Issue by happyme531** [arduino/arduino-pro-ide#288]
**Describe the bug**
Only .ino files have code highlight and intellisense, other files (such as .cpp , .c or .h) show up like plain text.

**To Reproduce**
1.Open a project with more than one file other than .ino file.

**Expected behavior**
Files such as .c .cc .cpp .h .hpp .S should behave same as .ino.

**Screenshots**
![捕获](https://user-images.githubusercontent.com/20812356/87247430-648f5c00-c486-11ea-9237-fd5c1bab3443.JPG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version 0.06

**Comment by kittaakos** [comment]
Thank you for reporting it. It is the same as https://github.com/arduino/arduino-pro-ide/issues/257. It has been fixed, but not yet released. I am closing this issue.
