### ISSUE TITLE
GCC complier flags

### ISSUE THREAD

**Issue by trlafleur** [arduino/arduino-pro-ide#289]
The IDE, using the variant.h file knows what CPU the user has selected and then can make a decision on the proper flags to invoke to build the project...

On the compile line is uses the "-mcpu" to define the CPU family to use. "-mcpu=cortex-m4".
This information should ALSO be added as a  "-D"  flag, to give a consistent format for the user to determine the processor class he is using at run time.  -Dcortex-m4

Also as the IDE knows the exact processor it using from the variant.h file, it should also be added as a -D flag. 
-D__SAMD51G19A__ 

In reviewing a number of variant.h file, it's very inconsistent from manufacturer to manufacturer on what -D flags are included.

Doing this would add a very consistent format that code developers could depend on...

**Comment by per1234** [comment]
Since this isn't something that would be implemented in the Arduino Pro IDE's codebase, I'll close this so that the discussion can confined to a single issue https://github.com/arduino/Arduino/issues/10496.
