### ISSUE TITLE
LiquidCrystal:begin: error

### ISSUE THREAD

**Issue by MaybeMichal** [arduino/arduino-pro-ide#290]
I am trying to make i2c projects with arduino and i allways get the same error as such in the title i tryed every salution... for example deleting all other liquid crystal librarys and install the right library that matches the code but still i have even reinstall the whole Arduino IDE still the same please if its someone out there who knows the salution i am begging you help me! Thank you.

**Comment by per1234** [comment]
Hi @MaybeMichal. This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your code, using code tags (`</>` button on the toolbar).
