### ISSUE TITLE
Support for Java programming language

### ISSUE THREAD

**Issue by zipCoder933** [arduino/arduino-pro-ide#291]
This feature is not related to a problem, however, It would be really amazing if you could add support for the Java programming language.

C++ is okay, but lacks the OOP side of Java.
If Java could be added to the IDE, it would make creating large projects much easier. Java is also much better at debugging than C or C++

**Comment by ubidefeo** [comment]
hey @zipCoder933 
I believe there is a misunderstanding.
This IDE is for Arduino and microcontrollers implemented using our cores structures.
It is not at all a general purpose IDE.
You should look into VS Code
