### ISSUE TITLE
All colors are faded, hard to see, how can I adjust them myself?

### ISSUE THREAD

**Issue by selevo** [arduino/arduino-pro-ide#292]
Thank, arduino pro ide - it's a good idea!

**Describe the bug**
All colors are faded, hard to see, how can I adjust them myself?

OS WIN 7

![ScreenShot002307](https://user-images.githubusercontent.com/13694921/88448933-e5216580-ce53-11ea-9646-1c61fce4bc5d.jpg)

**Comment by kittaakos** [comment]
You can pick another color theme:
 - Open the _Command Palette_ (<kbd>F1</kbd> or <kbd>Ctrl/⌘</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>)
 - Execute the `Preferences: Color Theme` command,
 - Pick another theme.

I hope this helps.

![screencast 2020-07-27 16-56-57](https://user-images.githubusercontent.com/1405703/88557521-9aa61180-d02a-11ea-9016-7aff63beb6d4.gif)

**Comment by Master811129** [comment]
> You can pick another color theme:
> 
> * Open the _Command Palette_ (F1 or Ctrl/⌘+Shift+P)
> * Execute the `Preferences: Color Theme` command,
> * Pick another theme.
> 
> I hope this helps.
> 
> ![screencast 2020-07-27 16-56-57](https://user-images.githubusercontent.com/1405703/88557521-9aa61180-d02a-11ea-9016-7aff63beb6d4.gif)

WOW so many theme! can we see them in the next release?

**Comment by selevo** [comment]
Thanks, but I asked how to change the color myself, I was not interested in other people's schemes.

And second, I only have 4 color schemes, what am I doing wrong?
![2020-07-29~07_01_27](https://user-images.githubusercontent.com/13694921/88751895-a815e580-d169-11ea-862f-bd4e1d46da5d.gif)

**Comment by kittaakos** [comment]
> Thanks, but I asked how to change the color myself, I was not interested in other people's schemes.

This is not yet ~supported~ available, but I do not see any technical obstacles; the idea is the following:
 - The Arduino Pro IDE is based on [Eclipse Theia](https://theia-ide.org/),
 - Theia can run any VS Code extensions,
 - In theory, you can install and run any VS Code extensions, including themes,
 - You can [craft](https://code.visualstudio.com/api/extension-guides/color-theme#create-a-new-color-theme) your own color theme and publish it to for instance [Open VSX registry](https://open-vsx.org/),
 - You can install and consume it from the Pro IDE.


> And second, I only have 4 color schemes, what am I doing wrong?

Nothing. The latest publicly available release was rolled out months ago.
