### ISSUE TITLE
macOS: Command + r is hijacked globally

### ISSUE THREAD

**Issue by j-rieck** [arduino/arduino-pro-ide#298]
**Describe the bug**
When Arduino Pro IDE is running in the background, <kbd>⌘</kbd> <kbd>R</kbd> is hijacked globally, preventing other applications from utilising it.

**To Reproduce**
1. Open Arduino Pro IDE
2. Switch to a browser
3. Hit <kbd>⌘</kbd> <kbd>R</kbd> on the keyboard
4. Watch as nothing happens
5. Close Arduino Pro IDE
6. Repeat step 2.
7. The page will now reload

**Expected behavior**
It is expected that <kbd>⌘</kbd> <kbd>R</kbd> will only trigger within Arduino Pro IDE when the application is the currently active one.

**Screenshots**
![Screenshot 2020-08-07 at 10 49 35](https://user-images.githubusercontent.com/92220/89627824-f2dede00-d88a-11ea-8dfa-92ec28d77b55.png)

**Desktop (please complete the following information):**
 - OS: macOS 10.15.5
 - Arduino Pro IDE 0.0.6 (0.0.6.20200409.2)

**Additional context**
Captured with ShortcutDetective

**Comment by j-rieck** [comment]
I just checked out the eclipe-theia repository, and it seems there was a change three months ago in [this  commit](https://github.com/eclipse-theia/theia/commit/8ca3e6459362320f26f80a7e072eacc7d09ceb4a).

"Removed global shortcuts if window is not focused." Is the Arduino Pro IDE running on a version before this commit? If so, that would explain the issue.

**Comment by ubidefeo** [comment]
hi @j-rieck 

first of al: great icon!
on to the serious stuff: we have fixed this in the meantime, and a new realease is on its way with many more changes.
We're planning a better schedule for updates on this project, but decided to first address most of the annoying things before pushing a new one out.

The wait is not gonna be long, we're days away :)

**Comment by j-rieck** [comment]
Moof!

Thanks for the update, looking forward to the release, and the eventual release of the source code.

Thanks for your hard work!

**Comment by kittaakos** [comment]
@j-rieck, [here](https://github.com/arduino/arduino-pro-ide/issues/249#issuecomment-628531565) is a workaround if you cannot wait until the next release.

**Comment by j-rieck** [comment]
Thanks @kittaakos. I didn't think of searching closed issued before opening this one.

**Comment by kittaakos** [comment]
Fixed. Closing.
