### ISSUE TITLE
Incorrect string literal highlighting in dark theme with "%" character

### ISSUE THREAD

**Issue by spacegaier** [arduino/arduino-pro-ide#3]
**Describe the bug**
"%" is in red font color instead of the orange that the rest of the string literal uses.

**To Reproduce**
1. Start IDE with dark theme.
2. New INO file with source code: const char* string = "string%withPercent";

**Expected behavior**
All orange font for string literal.

**Screenshots**
![test](https://user-images.githubusercontent.com/114137/67146442-63305a80-f28b-11e9-875f-7d673fe82f72.png)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Version 0.0.1

**Comment by svenefftinge** [comment]
I cannot reproduce this on OSX with the next milestone (v0.0.3).
<img width="317" alt="Screenshot 2019-11-28 at 09 15 41" src="https://user-images.githubusercontent.com/372735/69788920-bddca080-11bf-11ea-9800-6e1d6635056a.png">

**Comment by spacegaier** [comment]
It seems to depend on the actual string literal. Your "foo%test" also works fine for me, but my original test value still has the wrong highlight in v0.0.3 as does a simple value like "a%b". "a%a" however is weirdly fine.
![grafik](https://user-images.githubusercontent.com/114137/71868262-b63cdf80-310d-11ea-8afe-201fc33bea9d.png)

**Comment by spoenemann** [comment]
That's because the highlighting supports _format specifiers_ used by [printf](http://www.cplusplus.com/reference/cstdio/printf/) and other standard functions. It does not check whether the string is actually used within a call to `printf`, but that's a limitation we cannot overcome.
