### ISSUE TITLE
Missing "File - Open Folder" option

### ISSUE THREAD

**Issue by OslafEman** [arduino/arduino-pro-ide#321]
Hello @ubidefeo, thank you for your prompt reply. I confirm that I am using the Advanced Mode of the IDE.

I'm sorry, I accidentally opened a new issue.

![Anotación 2020-08-26 113425](https://user-images.githubusercontent.com/43764333/91331695-b2d79080-e790-11ea-8c06-c2f579937800.png)

**Comment by per1234** [comment]
Hi @OslafEman. I've transfered your reply back to the original issue you created (https://github.com/arduino/arduino-pro-ide/issues/317). I'm going to close this one so we can keep all the discussion on this topic in one place for easy reference. You are always welcome to open new issues for unique bug reports or feature requests.

Regards, Per
