### ISSUE TITLE
0.1.1 (etc.) console "error" string text too dull to easily read when using "Arduino (light)" color scheme

### ISSUE THREAD

**Issue by paschlie** [arduino/arduino-pro-ide#324]
This is really a problem with the non-pro version as well, error messages are nearly impossible to read, being displayed as very dull red text against a dark background; please brighten to be similar to the red used by (dark) schemes (as error messages should not be difficult to read).  Thanks.

**Comment by kittaakos** [comment]
@paschlie, I can see that the theme causes some frustration on your side, we got the message from your [previous GH issue](https://github.com/arduino/arduino-pro-ide/issues/310) too. Unfortunately, we have [not received a single](https://github.com/arduino/arduino-pro-ide/issues/310#issuecomment-679304706) screenshot depicting the UI/UX problem:

> @paschlie, can you please attach a screenshot to the issue?

Can you please attach a screenshot just to see how bad the situation is?

As a workaround, please use the Arduino theme, that's a light one and the default 😄

**Comment by paschlie** [comment]
Using the "Arduino (light)" theme (which uses a dark background console display like (dark) themes but for some reason the "red" in dark themes is brighter; maybe the two different red fonts should be used, a darker one for light backgrounds, and a brighter one for dark backgrounds):

![Screen Shot 2020-08-31 at 8 43 32 AM](https://user-images.githubusercontent.com/60820378/91721623-1124ba80-eb67-11ea-9e5a-7bfd6e11b5af.png)

**Comment by kittaakos** [comment]
Thank you for the update, we will keep your feedback in mind when it comes to the theme updates 👍

**Comment by kittaakos** [comment]
The foreground color of the font is always white in the _Output_, no matter it was an error or not.

![Screen Shot 2020-12-01 at 10 31 38](https://user-images.githubusercontent.com/1405703/100722133-8ef39e80-33c0-11eb-8fee-0f75bc37d4cb.jpg)

Closing.
