### ISSUE TITLE
Progress display of some sort

### ISSUE THREAD

**Issue by OMGdaDPS** [arduino/arduino-pro-ide#33]
When installing boards from the boards manager, it just shows "installing x board. please wait". Maybe it would be a good idea to either focus the screen on the terminal (which happens to be greyed out and in the background of the "progress" window) that shows the actual installation, or maybe have a progress bar inside of the actual window itself. Or maybe un-dim the back drop when the "installing x board. please wait" window is shown.

**Comment by nikilase** [comment]
Duplicate of #11

**Comment by mastrolinux** [comment]
Closing as duplicate

**Comment by OMGdaDPS** [comment]
mine sounds better though (kek)
