### ISSUE TITLE
Auto Save

### ISSUE THREAD

**Issue by imagidan** [arduino/arduino-pro-ide#331]
I would recommend putting it in the top menu > tools or in top menu > file

**Comment by ubidefeo** [comment]
Auto-save is in the preferences, but I know that VS Code has it as a flag in the main menu.
I have nothing against this feature, just don't really see a need for it to be another menu item when it's available in the preferences :)
I'm not a fan of redundancy :D

**Comment by imagidan** [comment]
Closed issue since now I know it is already a feature thanks to @ubidefeo
