### ISSUE TITLE
Code Completion and Syntax interpreter do not recognize any arduino features

### ISSUE THREAD

**Issue by VoidStoneDev** [arduino/arduino-pro-ide#342]
![Naamloos](https://user-images.githubusercontent.com/67163402/92308834-e8565800-efa0-11ea-888b-93e0cc3656b5.png)
![Naamloos2](https://user-images.githubusercontent.com/67163402/92312650-092fa500-efc3-11ea-9389-14e848150f5d.png)

None of the basic functions, variables, and constants are in code completion and Syntax checking.

ps. Arduino AVR Boards is installed, and code does actually compile

EDIT: seems like it is a issue with #include because functions from custom header files als do the above

**Comment by ubidefeo** [comment]
should work as of `0.1.4`
