### ISSUE TITLE
Pin Numbering

### ISSUE THREAD

**Issue by Docara** [arduino/arduino-pro-ide#345]
Hello

I have just started using Arduino for quick project development for standalone MCU development mainly because of the range of libraries - I usually use Flowcode.

One thing which often really hinders me is being _**forced**_ to use the Arduino pin number designations. As this is spouted as a 'PRO' IDE is the option I would like to have the **_option_** to use standard pin numbers on the chip eg PB1, PA3 etc and not 13.

I know this seems trivial but when you are looking at a datasheet for a given MCU they do not give the Arduino designations - you then have to find a pin schematic to cross reference the data sheet and Arduino numbering system.

I know this is slightly outside the original remit of Arduino but the usage of this IDE has mushroomed outside the original design brief for beginners and like I said this is for the PRO version.

Thanks

**Comment by per1234** [comment]
> I would like to have the option to use standard pin numbers on the chip eg PB1, PA3

Be aware that these are only convenience macros defined to the bit number of that pin:
```c++
#define PORTB1 1
```
```c++
#  define PB1 PORTB1
```
so `PB1` == `PA1`


As for direct direct port manipulation, you are and always have been able to do this with any Arduino development software. The only limitation is that the standardized Arduino core API and official library functions use Arduino pin numbers. However, you're welcome to use low level code to do it. You can find more information on that here:
https://www.arduino.cc/en/Reference/PortManipulation
