### ISSUE TITLE
“Upload Using Programmer” with “Arduino as ISP” programmer doesn’t work

### ISSUE THREAD

**Issue by kittaakos** [arduino/arduino-pro-ide#347]
Originally reported by @per1234:

 - Turn an Arduino board into an “Arduino as ISP” programmer as shown in this tutorial: https://www.arduino.cc/en/Guide/ArduinoISP
 - Connect the “Arduino as ISP” to the target AVR board.
 - From the board menu, select the board for the target board, and the port of the “Arduino as ISP” board.
 - Tools > Programmer > Arduino as ISP
 - Sketch >  Upload Using Programmer

The process fails:
```
Uploading...
{
  "sketchUri": "file:///tmp/.arduinoProIDE-unsaved2020721-3289-1qbl75w.97q/sketch_aug21a/sketch_aug21a.ino",
  "fqbn": "arduino:avr:uno",
  "optimizeForDebug": false,
  "programmer": {
    "id": "arduinoasisp",
    "name": "Arduino as ISP",
    "platform": "arduino:avr@1.8.3"
  }
}
--------------------------
Upload error: Error: 2 UNKNOWN: programming error: no upload port provided
```

Unlike the other programmers, which are pure USB devices, the “Arduino as ISP” programmer requires a serial port selection.

I should clarify that the above is the full set of steps that should achieve a successful “Upload Using Programmer” with the “Arduino as ISP” programmer. If you only want to reproduce the bug, these steps are sufficient:

 - Select any board of the Arduino AVR Boards platform from the board menu.
 - Select any port
 - Tools > Programmer > Arduino as ISP
 - Sketch >  Upload Using Programmer

With a correctly working IDE, this minimal set of steps will still be expected to fail due to not having an  Arduino as ISP programmer connected to the computer, but it should fail with these errors:
```
avrdude: stk500_recv(): programmer is not responding
avrdude: stk500_getsync() attempt 2 of 10: not in sync: resp=0x00
```

**Comment by ubidefeo** [comment]
this has long been resolved
