### ISSUE TITLE
cannot upload on ubuntu 20.04 Permission denied

### ISSUE THREAD

**Issue by Master811129** [arduino/arduino-pro-ide#349]
**Describe the bug**

I can't upload.

```
Uploading...
 {
  "sketchUri": "file:///home/ali/Arduino/ROT13/ROT13.ino",
   "fqbn": "arduino:avr:leonardo",
  "optimizeForDebug": false,
  "port": "/dev/ttyACM0"
}
--------------------------
Cannot perform port reset: opening port: Permission denied
avrdude: ser_open(): can't open device "/dev/ttyACM0": Permission denied
Upload error: Error: 2 UNKNOWN: uploading error: uploading error: exit status 1
```
**To Reproduce**
1. Click on 'upload'
2. See error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/37829730/92617519-9ed57800-f2d4-11ea-8949-531dfe44398c.png)

**Desktop (please complete the following information):**
 - OS: linux ubuntu
 - Version 20.04

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules. Be sure to post your full error output, using code tags (`</>` button on the toolbar).
