### ISSUE TITLE
Boards Manager Bugs

### ISSUE THREAD

**Issue by Maherulazam** [arduino/arduino-pro-ide#35]
Can't scroll in the Boards Manager (No Scroll Bar) and the search is not working as well. 

![Barads Manager Scroll Bug](https://user-images.githubusercontent.com/37402682/67157759-a1448180-f352-11e9-964f-13e7df91b484.jpg)
![Boards Manager Search Bug](https://user-images.githubusercontent.com/37402682/67157760-a1dd1800-f352-11e9-84c0-0e50bfab3636.jpg)

Can't detect the Arduino Uno connected to COM38.

![Port Detection Bug](https://user-images.githubusercontent.com/37402682/67158015-b7ebd800-f354-11e9-93e7-81f81229921a.jpg)
![Port Detection Bug2](https://user-images.githubusercontent.com/37402682/67158016-b7ebd800-f354-11e9-8275-b15eeb353d35.jpg)

**Comment by rsora** [comment]
Hi @Maherulazam  , thanks for your report!

I see form your screenshot that you are on a Windows OS, could you please add the version of your Operating system to the issue description?

In the meantime, can you please check if the snapshot builds attached here https://github.com/arduino/arduino-pro-ide/issues/51#issuecomment-544560707 solve your detection problem?

Thanks!

**Comment by Erriez** [comment]
Same problem for me on Windows 10 64-bit: No serial port found, but multiple serial ports are listed in the original IDE and Windows device manager.

**Comment by mastrolinux** [comment]
Can you please try again with the last build available at https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.1-alpha.preview-snapshot-20191021.1 and let us know?

**Comment by Erriez** [comment]
The scrollbar is now visible on my Windows 10 computer and I am able to select the Arduino UNO board with _Arduino Pro IDE Windows v0.0.1-alpha.preview-snapshot-20191021.1:_

![image](https://user-images.githubusercontent.com/8849873/67419497-16bb8680-f5cd-11e9-95cb-9ce2713cc981.png)

Serial ports not detected is still a Major issue on all platforms:

- https://github.com/arduino/arduino-pro-ide/issues/75
- https://github.com/arduino/arduino-pro-ide/issues/78
- https://github.com/arduino/arduino-pro-ide/issues/86

**Comment by kittaakos** [comment]
This has been fixed. I am going to close it.

----

Longer story:
Previously we collected only those boards that have an FQBN, it was incomplete logic.
Now, we collect all boards that have an FQBN, plus we collect all used ports:
```json
[
  {
    "address": "/dev/cu.SOC",
    "protocol": "serial",
    "protocol_label": "Serial Port"
  },
  {
    "address": "/dev/cu.MALS",
    "protocol": "serial",
    "protocol_label": "Serial Port"
  },
  {
    "address": "/dev/cu.Bluetooth-Incoming-Port",
    "protocol": "serial",
    "protocol_label": "Serial Port"
  },
  {
    "address": "/dev/cu.usbmodem14601",
    "protocol": "serial",
    "protocol_label": "Serial Port (USB)",
    "boards": [
      {
        "name": "Arduino MKR1000",
        "FQBN": "arduino:samd:mkr1000"
      }
    ]
  },
  {
    "address": "/dev/cu.usbserial-0001",
    "protocol": "serial",
    "protocol_label": "Serial Port (USB)"
  }
]%  
```
In the above example, there is an attached `Arduino MKR1000` ( on `/dev/cu.usbmodem14601`) and an ESP8266 (on `/dev/cu.usbserial-0001"`).

![Screen Shot 2020-04-08 at 11 22 34](https://user-images.githubusercontent.com/1405703/78767743-4566c700-798b-11ea-8ff6-7c2bafd255ca.jpg)

Furthermore, we have better support for 3rd party, "unknown" boards: https://github.com/arduino/arduino-pro-ide/issues/198#issuecomment-600059664
