### ISSUE TITLE
Please move the "Outline View" icon and display to the left hand side of the window

### ISSUE THREAD

**Issue by paschlie** [arduino/arduino-pro-ide#354]
with all the other feature activating/view icons, so its presence won't unnecessarily use screen real estate on the right side of the window.

**Comment by sstaub** [comment]
Do it like VSCode please

**Comment by kittaakos** [comment]
Thanks for letting us know.

For the record: the default, classic layout does not include the Outline view; if you want to gain an additional 50 px, you can right-click on it and select _Close_.

![image](https://user-images.githubusercontent.com/1405703/93113901-2565cd00-f6ba-11ea-9841-120229efb0db.png)

**Comment by paschlie** [comment]
> Thanks for letting us know.
> 
> For the record: the default, classic layout does not include the Outline view; if you want to gain an additional 50 px, you can right-click on it and select _Close_.

Thank you, however no such thing appears on macos 10.13.6 right-click (presumably a ctrl-click) to remove the right-hand control icon column, and corresponding outline control icon positioned there,  the only thing any type of click on the outline icon does is to toggle the display of the outline pane, which doesn't itself appear to work yet.

Maybe this is should really be a personal choice, users should be able to decide whether to place icons to enable certain features on the right or left hand columns, and such that if none are placed in one or the other, the space reverts for use by the editor/console sub-windows.  But if too complicated, then maybe all control icons should be placed in the left hand icon column, as someone else noted VSCode does; as having both if non-configurable, arguably just takes up space and adds little if any utility.

(As an aside, the minimum window sizes have already been made too large to be properly displayed on smaller screens; saving strictly unnecessary use of window space can only help the situation.)

**Comment by kittaakos** [comment]
> however no such thing appears on macos

Strange, it works for me:

![screencast 2020-09-15 09-00-28](https://user-images.githubusercontent.com/1405703/93176782-10c51b80-f732-11ea-8a98-43403c60fe09.gif)

**Comment by paschlie** [comment]
Please notice the "outline view" icon is always present without any way to disable it with any key-click combination I can find:
![Screen Shot 2020-09-15 at 9 33 57 AM](https://user-images.githubusercontent.com/60820378/93217315-e88beb80-f736-11ea-8b89-34cbcb9cf061.png)


And when "outline view" is displayed, it does not contain anything useful on my installation, and never noticed it ever doing so?:
![Screen Shot 2020-09-15 at 9 33 40 AM](https://user-images.githubusercontent.com/60820378/93217328-ec1f7280-f736-11ea-9c69-9c41297869be.png)

**Comment by kittaakos** [comment]
> And when "outline view" is displayed, it does not contain anything useful on my installation, and never noticed it ever doing so?:

You have to pick a board to start the language server and have the _Outline_ view populated. (See the specification for `'textDocument/documentSymbol'` [here](https://microsoft.github.io/language-server-protocol/specification.html#textDocument_documentSymbol) if you're interested.)

**Comment by paschlie** [comment]
Selecting a board doesn't seem to make any difference, but if significant here are the messages present after selecting the board (and not sure why it should make a difference, but why can't the "outline view" icon and corresponding right-hand icon column be dismissed, does it somehow rely on "outline-view" working properly?):
![Screen Shot 2020-09-15 at 9 50 42 AM](https://user-images.githubusercontent.com/60820378/93219684-9d270c80-f739-11ea-8a9a-0667651ba3a3.png)

**Comment by paschlie** [comment]
[2020-09-15_log.log](https://github.com/arduino/arduino-pro-ide/files/5225462/2020-09-15_log.log)

**Comment by kittaakos** [comment]
> so its presence won't unnecessarily use screen real estate on the right side of the window.

> Do it like VSCode please

Thank you for your feedback; I moved it to the left side.

Classic mode:
![354_classic_mode](https://user-images.githubusercontent.com/1405703/93319469-2f014900-f810-11ea-9474-423a9ae75109.gif)

Advanced mode:
![354_advanced](https://user-images.githubusercontent.com/1405703/93319446-290b6800-f810-11ea-97b1-3ad9a750bea7.gif)


The change will be available with one of the nightly builds this week or next week.

**Comment by paschlie** [comment]
Has this change been published in the nightly build? (I didn’t notice any change log entry?)

**Comment by kittaakos** [comment]
> Has this change been published in the nightly build? (I didn’t notice any change log entry?)
> […](#)

No, not yet. 👇 

> The change will be available with one of the nightly builds this week or next week.

**Comment by paschlie** [comment]
Thanks, I’m assuming from your posting that if “outline view” is toggled on, its icon remains in the left hand icon doc, from where its view pane may be expanded or contracted with a click on its icon as may be desired?
