### ISSUE TITLE
Allow creating .gitignore

### ISSUE THREAD

**Issue by portasynthinca3** [arduino/arduino-pro-ide#359]
**Is your feature request related to a problem? Please describe.**
In Git, `.gitignore` is an important file. However, when I try to create it, the IDE doesn't let me do so, saying it's "not a valid file extension"

**Describe the solution you'd like**
Allow any file names and extensions when creating a new file.

**Describe alternatives you've considered**
Whitelist `.gitignore` as a valid file extension when creating a new file.

**Additional context**
Screenshot:
![image](https://user-images.githubusercontent.com/14039901/93635760-83b4e780-f9fb-11ea-8791-eb3d568c49d0.png)

**Comment by per1234** [comment]
Hi @portasynthinca3. Thanks for taking the time to submit a feature request.

I see we have another issue for the same request. Even though that one came after this, it is more broadly titled (in line with your recommended solution of allowing arbitrary file extensions)

It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this in favor of the other.
If you end up with additional information to share, feel free to comment in the other thread.
