### ISSUE TITLE
I can't search boards and can't select the port

### ISSUE THREAD

**Issue by jbiel09** [arduino/arduino-pro-ide#36]
I can't search boards and a can't select the port. I'm from brazil, sorry i don't speak english very well but I expect help you

**Comment by nikilase** [comment]
What OS are you on? If on Linux, have you added your user to the group dialout. I think you can do this with `sudo adduser YOUR_USER dialout`
Otherwise, have you installed your board in the board manager? It can be opened under Tools -> Board Manager

**Comment by DrKsantor** [comment]
In windows this behavior occurs when Arduino-Pro located in Program Files (folder with administrative permissions) and run not as administrator.

**Comment by rsora** [comment]
Hi @jbiel09 , thanks for your report!

Can you please check if the snapshot builds attached here https://github.com/arduino/arduino-pro-ide/issues/51#issuecomment-544560707 solve your problem?

Thanks!

**Comment by pranjal991** [comment]
> In windows 10 this behavior occurs when Arduino-Pro located in Program Files (folder with administrative permissions) and run not as administrator.
> Solving ways:
> 
> 1. Run as administator
> 2. Locate IDE files somewhere else.

For me it worked in different way:
1.Run normally/administrator
2.IDE files located in C drive
 
But only boards issue is resolved ,not the ports issue still ports are not visible.
![Capture](https://user-images.githubusercontent.com/56870966/67276493-6a9d7100-f4e2-11e9-945b-6e03e7791b30.PNG)

**Comment by mastrolinux** [comment]
Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview

**Comment by mastrolinux** [comment]
Closing because no feedback
