### ISSUE TITLE
Has Anyone Tried The Pro IDE in WSL?

### ISSUE THREAD

**Issue by jwestmoreland** [arduino/arduino-pro-ide#363]
Opening this again, since it's a legitimate question.

Has anyone here tried the Pro IDE is WSL?  (Windows Subsystem for Linux).

Regards,
John W.

**Comment by jwestmoreland** [comment]
#360 closed unanswered.

**Comment by per1234** [comment]
This issue tracker is only to be used to report bugs or feature requests. This topic is more appropriate for the Arduino Forum.
