### ISSUE TITLE
App don't close by Confirm Exit 

### ISSUE THREAD

**Issue by harryberlin** [arduino/arduino-pro-ide#367]
**Describe the bug**
After setting the request before close application. the app don't close after dialog. it's equal yes or no. the app will not close.
Reset to "ifrequeird" has no effect. The Dialog pops up always.
**To Reproduce**
1. Go to 'perfences'
2. Click on 'confirm exit'
3. Select 'always'
4. Try to close the application.

**Expected behavior**
kill process from taskmanager

**Screenshots**
No Screenshot.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Version: 10 64-bit

**Additional context**
No other context about the problem here.

**Comment by kittaakos** [comment]
Thank you for reporting it, @harryberlin. It's tracked under #315.

Here is a workaround for the time being: https://github.com/arduino/arduino-pro-ide/issues/315#issuecomment-680159982

I am closing it. Please ping me if you disagree. Thanks!
