### ISSUE TITLE
error when #include "Arduino.h" on macOS 

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#368]
**Describe the bug**
see screenshot, I got an error (but I can compile) when I include Arduino.h

```
In included file: Unsupported architecture
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/sys/cdefs.h:807:2:
note: error occurred hereclang(pp_hash_error)
```

I know that Including Arduino.h is not needed, but necessary when use in platformIO.
Maybe a general problem with Xcode because GCC is no more supported on Xcode 12.

**To Reproduce**
Create a file with `#include "Arduino.h"`

**Expected behavior**
there should no error

**Screenshots**
<img width="1482" alt="error in #include" src="https://user-images.githubusercontent.com/6450325/96334837-fef9cf80-1073-11eb-8b87-d3bf56a4fe48.png">

**Desktop (please complete the following information):**
 - OS: macOS 15.7
 - Xcode 12
 - Version: 0.1.2 nightly

**Additional context**

**Comment by ubidefeo** [comment]
@sstaub 
this is not an error for the IDE, the sketch compiles fine and that header is automatically added to any Arduino sketch compilation process.
I can imagine the highlight as an error bothers you, but it should not be a big concern

**Comment by per1234** [comment]
Hi @sstaub . Thanks so much for taking the time to report this!

This should now be working in [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you try it out and find that the problem is still occurring, feel free to comment here and we'll investigate.
