### ISSUE TITLE
Copy the text in the Output box also copy the sketch code and other text

### ISSUE THREAD

**Issue by Fede85** [arduino/arduino-pro-ide#37]
When you try to copy the text in the "Output" box, the sketch and other text are also copied.

**To Reproduce**
1.Open any sketch, some INFO text should appear in the Output box
2. Click on the "Output box" and copy the text with "CTRL+A"
3. Copy the text on another text editor

**Expected behavior**
Only the text in the Output box should be copied.

**Desktop:**
 - OS: Windows
 - Version 10

Example:
```
uno
1112345678910


void setup() {
// put your setup code here, to run once:

}

void loop() {
// put your main code here, to run repeatedly:

}

[INFO] Updating index [url: https://downloads.arduino.cc/packages/package_index.json]
Updating index: package_index.json completed.
[INFO] Loading hardware from: c:\Users\Federico\AppData\Local\Arduino15\packages
[INFO] Loading package arduino from: C:\Users\Federico\AppData\Local\Arduino15\packages\arduino\hardware
[INFO] Loaded platform [platform: {ID:"arduino:mbed",Installed:"1.1.0",Latest:"1.1.2",Name:"Arduino nRF528x Boards (Mbed OS)"}]
[INFO] Loaded platform [platform: {ID:"arduino:samd",Installed:"1.6.20",Latest:"1.8.4",Name:"Arduino SAMD Boards (32-bits ARM Cortex-M0+)"}]
[INFO] Checking existence of 'tools' path: C:\Users\Federico\AppData\Local\Arduino15\packages\arduino\tools
...[trimmed]
```

**Comment by per1234** [comment]
Closing as fixed by https://github.com/eclipse-theia/theia/pull/7523

@Fede85, if you give [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4) and find you're still having this issue, please comment here and I'll reopen. Thanks so much for reporting this issue!
