### ISSUE TITLE
please consider embracing PlatformIO

### ISSUE THREAD

**Issue by paschlie** [arduino/arduino-pro-ide#372]
As after using this tool over the past few weeks as an extension to VSCode, it's hard to imagine it being productive to re-create; so instead it may be best to concentrate further development efforts on things specific to the Arduino API, basic RTOS, libraries, products, and integration support as may be further required to improve Arduino development and debugging, not re-creating what already effectively exists and quite pleasant to use (like possibly further developing and refining examples which beginners can learn from, and easily incorporate/extend into their own projects.)

**Comment by ubidefeo** [comment]
hi @paschlie 
as already stated in the past they are two completely separate projects.

If you are happy using PlatformIO and it makes your workflows easy you should do so :)
