### ISSUE TITLE
Use of undeclared identifier with multiple .ino tabs project

### ISSUE THREAD

**Issue by novakkry** [arduino/arduino-pro-ide#383]
I have a project consisting of four .ino files. The program compiles just fine but while working on it, the IDE tells me "Use of undeclared identifier" error nearly everywhere besides the first tab. Also, for instance, variable suggestions works only in the first tab, not in the others. The sketch is saved in the default user sketchbook. If I put everything into the first tab, it behaves as expected.

**To Reproduce**
1. Create a multiple arduino tab project and put different components into each tab (eg. setup and loop to a second tab)

**Expected behavior**
Not showing false problems.

**Screenshots**
<img width="699" alt="Screenshot 2020-11-12 at 18 37 50" src="https://user-images.githubusercontent.com/63838905/98975259-2e3a1a00-2516-11eb-821d-f73086f89b49.png">
<img width="775" alt="Screenshot 2020-11-12 at 18 38 32" src="https://user-images.githubusercontent.com/63838905/98975341-46119e00-2516-11eb-8fe9-4a713fba6540.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.13
 - Version: Pro IDE 0.1.2

**Comment by novakkry** [comment]
Just noticed that the red underlying problems are being showed only on the current view of the tab. If you scroll down in a tab, it's not underlined anymore, only on the first a couple of lines.

<img width="1656" alt="Screenshot 2020-11-13 at 11 46 15" src="https://user-images.githubusercontent.com/63838905/99064164-d8ad4e00-25a5-11eb-89cf-c0fed9f51d1b.png">

**Comment by ubidefeo** [comment]
@novakkry 
A fix is in the making. We have reworked the Language Sever translator and will add the fix tot he next release.
Not sure you can disable the error highlighting, but if there is @kittaakos will have an answer for you :)

**Comment by novakkry** [comment]
> @novakkry
> A fix is in the making. We have reworked the Language Sever translator and will add the fix tot he next release.
> Not sure you can disable the error highlighting, but if there is @kittaakos will have an answer for you :)

That's awesome. Thank you, guys!

**Comment by ubidefeo** [comment]
resolved in `0.1.4 Alpha`
