### ISSUE TITLE
IDE is not recognizing project located libraries.

### ISSUE THREAD

**Issue by MenTom-CZ** [arduino/arduino-pro-ide#387]
**Describe the bug**
IDE is not recognizing project located libraries.
There is problem. When I try to incluce my library in project folder. IDE don't know about library (highlighting every usage of library in sketch(variables, functions) and tells me that everything used is undeclared) but when I try to compile my project everything isfine and compilation is succesful but ide still shows errors.

**To Reproduce**
1. In project folder create any .h file and add some content
2. Include that file with #include "FILENAME.h"
3. Try to acces content of file (function, variable, definition)
4. Content will bee highlighted as "Use of undeclared identifier"

**Expected behavior**
IDE should show tooltips and not highlight elements as udeclared/undefined.

**Screenshots**
![2020-11-20 143925](https://user-images.githubusercontent.com/48769727/99806368-3dd0e880-2b3e-11eb-8327-231fa2711ed3.png)

**Desktop (please complete the following information):**
 - Windows 10

**Comment by ubidefeo** [comment]
@MenTom-CZ 
please check out #384 
this is a known bug we're working on

**Comment by ubidefeo** [comment]
resolved in `0.1.4 Alpha`
