### ISSUE TITLE
Library not found when compiling, but library is installed

### ISSUE THREAD

**Issue by Tonkaman** [arduino/arduino-pro-ide#388]
When compiling a project using the OBD2 library, compilation fails because the IDE cannot find the .h file.  The library is on my computer, and the sketch compiles just fine in the regular Arduino IDE.  When browsing the Library Manager, the library both shows as installed and with the option to install, as if it wasn't already installed.  The version in the Library Manager shows as 0.0.0.

**Screenshots**
![2020-11-21](https://user-images.githubusercontent.com/74835093/99889057-d55a3800-2c1f-11eb-98bc-a07c70d9bcc4.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - Version: Build 10.0.19041

**Additional context**

**Comment by ubidefeo** [comment]
hi @Tonkaman 
can you copy/paste your CLI configuration file?
You can get there from the menu **File > Open CLI configuration**

**Comment by Tonkaman** [comment]
board_manager:
  additional_urls: []
daemon:
  port: "50051"
directories:
  data: C:\Users\Jason\AppData\Local\Arduino15
  downloads: C:\Users\Jason\AppData\Local\Arduino15\staging
  user: C:\Users\Jason\OneDrive\Documents\Arduino
logging:
  file: ""
  format: text
  level: info
telemetry:
  addr: :9090
  enabled: true

**Comment by Tonkaman** [comment]
Here is the contents of the CLI:

board_manager:
  additional_urls: []
daemon:
  port: "50051"
directories:
  data: C:\Users\Jason\AppData\Local\Arduino15
  downloads: C:\Users\Jason\AppData\Local\Arduino15\staging
  user: C:\Users\Jason\OneDrive\Documents\Arduino
logging:
  file: ""
  format: text
  level: info
telemetry:
  addr: :9090
  enabled: true

**Comment by ubidefeo** [comment]
Thank you, @Tonkaman 
I trust that your library is in `C:\Users\Jason\OneDrive\Documents\Arduino\libraries`.
I have ran a few tests and this is the outcome.
I have installed the library and opened an example which seemed to be requiring `CAN.h`, which is not available through the library manager so I had to download it manually and place into `libraries` in my Sketch Folder.
I bumped into your exact issue until I tried with one of our more recent internal builds.
Please download a Nightly Build and your compilation problem should disappear
https://github.com/arduino/arduino-pro-ide#nightly-builds

Let me know if it doesn't :)

**Comment by Tonkaman** [comment]
@ubidefeo 
The nightly build solves the issue.  Thanks for looking into it.  I was using the last stable release, which was dated from September.

**Comment by ubidefeo** [comment]
@Tonkaman 
my pleasure :)
We're going to make another release soon, but trying to squeeze important fixes in it that address most complaints we've had so far.
The Nightly contains daily patches, and if you're willing to be on the edge it's the way to go ;)
