### ISSUE TITLE
No port discovered

### ISSUE THREAD

**Issue by Do4kgt** [arduino/arduino-pro-ide#397]
Hello everybody.

I had a total crash since yesterday. I had the mistake
13 Internal: Received RST_Stream with code 2 (Internal Server Error)

I then installed Git on Windows 10 and since then I can compile again.

however, since yesterday I can no longer select a board although it is recognized by the system.

I just can't choose a port and don't know what to do anymore.

![fail Arduini IDE](https://user-images.githubusercontent.com/61664243/102234297-7079c100-3ef1-11eb-8c46-55f741f3c182.jpg)

**Comment by Do4kgt** [comment]
noport

**Comment by kittaakos** [comment]
@Do4kgt, thanks for reporting.

 - Attach your board,
 - Open a terminal (e.g, `CMD.EXE`),
 - Run `path\\to\\the\\arduino\\IDE\\resources\\app\\node_modules\\arduino-ide-extension\\build\\arduino-cli.exe board list --format json`.

What is the output?

When I attach my Uno board, I see this:
```bash
C:\>Users\\kittaakos\\Desktop\\arduino-pro-ide_0.1.3-snapshot.08291f5_Windows_64bit\\resources\\app\\node_modules\\arduino-ide-extension\\build\\arduino-cli.exe board list --format json
[
  {
    "address": "COM3",
    "protocol": "serial",
    "protocol_label": "Serial Port (USB)"
  },
  {
    "address": "COM4",
    "protocol": "serial",
    "protocol_label": "Serial Port (USB)"
  },
  {
    "address": "COM7",
    "protocol": "serial",
    "protocol_label": "Serial Port (USB)",
    "boards": [
      {
        "name": "Arduino Uno",
        "FQBN": "arduino:avr:uno",
        "VID": "0x2341",
        "PID": "0x0043"
      }
    ]
  }
]

C:\>
```

**Comment by ubidefeo** [comment]
Closed for lack of information 2 months later.
