### ISSUE TITLE
IDE 0.1.3 Windows can not be unzipped

### ISSUE THREAD

**Issue by JSCLadon** [arduino/arduino-pro-ide#398]
When unzipping the IDE Windows 0.1.3 file, several files can not be unzipped and the process stops.

Thanks for looking into it.

**Comment by JSCLadon** [comment]
Sorry, my mistake, to embarrassing to tell anybody, what the problem was! ;-)

**Comment by JSCLadon** [comment]
.... was trying to extract into a remote directory on an unreliable connection....

**Comment by ubidefeo** [comment]
@JSCLadon 
don't feel bad about it, it's an honest mistake (trying to justify mine...)
