### ISSUE TITLE
No code completion on Mac

### ISSUE THREAD

**Issue by jtmaston** [arduino/arduino-pro-ide#406]
Hello! On a windows installation, I used to have autocompletion ( for things like `Serial` or the many variable types ) however, since I moved to Mac this feature is no longer available. Autocompletion does work with variables I have declared myself, however. I would like to note that I am on an older version of MacOS ( 10.11.6 ), so maybe that's the issue? Any help would be greatly appreciated.

**Comment by ubidefeo** [comment]
@jtmaston 
the auto-complete functionality is currently broken in Alpha
we're working towards a solution but it's proving to be a stubborn one

within a couple of weeks we should have an update regarding this issue,
but right now I can't estimate when it will be resolved

thank you
Ubi

**Comment by jtmaston** [comment]
Thank you for your input! Waiting enthusiastically!
