### ISSUE TITLE
Sketch Control button stops working after creating a new tab split

### ISSUE THREAD

**Issue by silvanocerza** [arduino/arduino-pro-ide#414]
**Describe the bug**

Moving a tab to create a new split in the editor UI disables the Sketch Control button for some seconds.

**To Reproduce**
1. Create a new sketch
2. Create a new tab 
3. Drag the tab to create a new split
4. Click any of the two Sketch Control buttons

The menu won't appear, clicking again after some seconds will work.

**Expected behavior**

I'd expect the Sketch Control button to always work.

**Desktop (please complete the following information):**
 - OS: Windows and Linux
 - Version: `snapshot.d9c793e`

**Additional context**
None.

**Comment by kittaakos** [comment]
> The menu won't appear, clicking again after some seconds will work.

Same as https://github.com/arduino/arduino-pro-ide/issues/335? Can you please check, @silvanocerza?

**Comment by silvanocerza** [comment]
Yep, seems like it's the same bug, just tested. I'll close this one in favour of the old issue.
