### ISSUE TITLE
FILENAME.h file is not found.

### ISSUE THREAD

**Issue by sebasdt** [arduino/arduino-pro-ide#415]
**Describe the bug**
the arduino pro ide can't find a local .h file that is in the same folder as in the main sketch file. while normal ide can.

audio.h is a file without a .cpp, i made it and consists lines of code for beat detection code. (i never had problems compiling this code)

![image](https://user-images.githubusercontent.com/67417070/107023451-f5bd7b80-67a6-11eb-98ba-eab44935a882.png)

**To Reproduce**
I don't know how I could reproduce. audio.h is as so far the only .h file that wouldn't get fetched by the pro ide.

**Expected behaviour**
the pro ide includes the local .h files without any problem

**Screenshots**
![image](https://user-images.githubusercontent.com/67417070/107021589-9fe7d400-67a4-11eb-8f3a-fba09e2c6a83.png)

![image](https://user-images.githubusercontent.com/67417070/107022451-b2164200-67a5-11eb-996e-9f0748b0aaea.png)

![image](https://user-images.githubusercontent.com/67417070/107022052-35836380-67a5-11eb-952e-13a1ba73a92e.png)

**Desktop (please complete the following information):**
 - OS: windows pro
 - Version:20H2

**Additional context**
I have made .h files so I could split up the code and have more oversight over the code. 
these .h files are in the same folder as the main sketch itself.

sorry if there's not enough data. just ask for more.

**Comment by ubidefeo** [comment]
@sebasdt 
can you try the latest Nightly Build?

**Comment by sebasdt** [comment]
yeah i can but where can i find it?
right now i use: arduino pro ide V0.1.3

**Comment by per1234** [comment]
@sebasdt download links for the Arduino Pro IDE nightly build are here:
https://github.com/arduino/arduino-pro-ide#nightly-builds

**Comment by sebasdt** [comment]
hi i'm back! it seems fixed!
but i get a interesting error back
No matching function for call to 'strcpy' note: candidate function not viable: requires 0 arguments, but 2 were provided
but it compiles and uploads without anyproblems

**Comment by ubidefeo** [comment]
@sebasdt , can you try and rename your `.h` into `.ino`?
it should solve your issue.
We'll address full support for `.h` in the near future

**Comment by sebasdt** [comment]
hi!

thanks for the help and the tip! 
it's solved for now!
