### ISSUE TITLE
Inconsistent default "Show verbose output during: compilation" setting

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-pro-ide#422]
**Describe the bug**

The **File > Preferences > Show verbose output during: compilation** preference is enabled by default. This is different from the precedent set by the Arduino IDE, where this preference is disabled by default.

The verbose compilation output shows all the compilation commands. These are very rarely useful for troubleshooting, but they are often a huge amount of text. This causes several problems for users:
- It's difficult to sift the useful warnings and error messages out of the mass of cryptic build commands.
- The unhelpful build commands cause the output to exceed the Arduino Forum's 9000 character post limit, meaning the user must post the output as an attachment, rather than directly in the forum thread. This harms the user because forum members are less likely to make the effort to download and open an attachment just to get an idea if the problem is something they might be able to help with. It harms the community because the keywords in the attachment content won't be found in web searches.

**To Reproduce**
1. Exit Arduino Pro IDE if it's running.
1. Rename `~/.arduinoProIDE/settings.json` to `~/.arduinoProIDE/settings.json.bak`
2. Start Arduino Pro IDE
3. **File > Preferences**
4. Verify that the box next to "Show verbose output during: compilation" is checked

**Expected behavior**

Arduino Pro IDE to use the same default **File > Preferences > Show verbose output during: compilation** setting as Arduino IDE.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 
    0.1.4-snapshot.3042c1a
    Date: 2021-02-08T10:04:20.854Z
    CLI Version: 0.15.1 alpha [c7403ed2]

**Additional context**

The default **File > Preferences > Show verbose output during: upload** setting is also different from the Arduino IDE's default. However, unlike the verbose compilation output, I think this is arguably an improvement. The verbose upload output serves as  a progress indicator and is also essential information for troubleshooting an upload failure.

**Comment by kittaakos** [comment]
It's done. One of the forthcoming releases will contain this change.
