### ISSUE TITLE
Copyright string is included in copied version information

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-pro-ide#423]
**Describe the bug**
When you copy the version information from the "About" dialog, the useless copyright notice is copied along with the useful version information.

The version information is very useful when writing bug reports, but I find it tedious to have to remove the copyright text every time.

**To Reproduce**

1. **Help > About Arduino Pro IDE**
2. Click the "Copy" button.
3. Paste the copied content somewhere. You will see the copyright notice at the end of the text:
    >Version: 0.1.4-snapshot.3042c1a
    >Date: 2021-02-08T10:04:20.854Z
    >CLI Version: 0.15.1 alpha [c7403ed2]
    >
    >Copyright © 2021 Arduino SA

**Expected behavior**
The copied content should only contain the useful information:
>Version: 0.1.4-snapshot.3042c1a
Date: 2021-02-08T10:04:20.854Z
CLI Version: 0.15.1 alpha [c7403ed2]

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 0.1.4-snapshot.3042c1a
    Date: 2021-02-08T10:04:20.854Z
    CLI Version: 0.15.1 alpha [c7403ed2]
    Copyright © 2021 Arduino SA (see!)

**Comment by kittaakos** [comment]
I have fixed it. It will be available soon.
