### ISSUE TITLE
File not getting saved on clicking SAVE and SAVE AS 

### ISSUE THREAD

**Issue by mishracodes** [arduino/arduino-pro-ide#438]
**Describe the bug**
Whenever we create a new file, it is being created in a temp directory 
**Eg. "file:///c%3A/Users/AMITKU~1/AppData/Local/Temp/.arduinoProIDE-unsaved2021118-7508-pe61f5.djye/sketch_feb18a/sketch_feb18a.ino"** 
now after making changes and when I try to save it, its not getting saved, it is giving warning that file do not exit or folder do not exist(screenshots attached)

**To Reproduce**
1.Click File> New
2.Make any changes to this file , by default its location will be in temp folder of user directory(as given above in description)
3.After making changes when tried to save using File>Save As
4. Save as dialogue Box appears and now the file is not being saved and getting error related to files and folders do not exist

**Expected behavior**
On clicking Save As and choosing any file name, the file should be saved as the given name.

**Screenshots**
[https://raw.githubusercontent.com/mishracodes/mishracodes.github.io/master/github%20Bugs/bug%201.png](url)
[https://raw.githubusercontent.com/mishracodes/mishracodes.github.io/master/github%20Bugs/bug%202.png](url)
[https://raw.githubusercontent.com/mishracodes/mishracodes.github.io/master/github%20Bugs/bug%204.png](url)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Single Language
 - Version: 10 Home, 64-bit os

**Comment by per1234** [comment]
Hi @mishracodes. Thanks for taking the time to report this bug. We already have a prior issue report about this at https://github.com/arduino/arduino-pro-ide/issues/430. It's best to have only a single issue per subject so we can consolidate all relevant discussion to one place, so I'll go ahead and close this as duplicate.

You'll be happy to see this comment from one of Arduino's developers:
https://github.com/arduino/arduino-pro-ide/issues/430#issuecomment-777512420
>I have fixed and verified it on Windows. We will make this available to the public soon.
