### ISSUE TITLE
Cannot see the full Arduino Pro IDE window on Linux (Ubuntu 20.04) laptop

### ISSUE THREAD

**Issue by LumitoLuma** [arduino/arduino-pro-ide#443]
**Describe the bug**
I cannot see the full Arduino Pro IDE window on my Ubuntu 20.04 (GNOME) laptop. I also cannot maximize it.

**To Reproduce**
1. Download Arduino Pro IDE 0.1.4 on Ubuntu 20.04
2. Extract
3. Open `arduino-pro-ide`

**Expected behavior**
Be able to fully resize the IDE window and maximize it.

**Screenshots**
![Error](https://user-images.githubusercontent.com/50250351/109157163-f75cdc80-7771-11eb-9335-3d264c99e89d.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint (with GNOME desktop, based on Ubuntu 20.04.1 LTS)
 - Version: 20.1 Ulyssa

**Additional context**
I also cannot vertically resize the window

**Comment by ubidefeo** [comment]
hi @LumitoLuma 
can you add your display resolution?

thanks

**Comment by kittaakos** [comment]
Thank you for reporting it, @LumitoLuma 👍 This is a known issue and tracked under https://github.com/arduino/arduino-pro-ide/issues/337. I am closing this one as a duplicate.

**Comment by kittaakos** [comment]
On a Windows machine, the resolution is 2560x1440, and the app is clipped. One has to maximize it to see the status bar. We cannot rely on fix height/width.
