### ISSUE TITLE
Arduino Pro IDE GUI is gone on Windows 10

### ISSUE THREAD

**Issue by jetzoc** [arduino/arduino-pro-ide#444]
**Describe the bug**
Opened up the Arduino Pro IDE (v0.1.4) and cannot see the GUI screen on Windows 10 machine. Splash screen shows up but there is no GUI interface. I downloaded the zip file opened the IDE once or twice but then switched to Linux and started to use the IDE there. Came back to Windows but now I don't see the GUI. I can hover over the taskbar and see a preview of the IDE but I do not see it at all. 

**To Reproduce**
1. Go to 'arduino-pro-ide_0.1.4_Windows_64_bit' folder
2. Click on 'Arduino Pro IDE.exe'
3. View the splashscreen
4. No GUI seen but can see the taskbar view

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/68865075/109231682-a5758000-778c-11eb-9cda-8686a6f2a4fe.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
I'm sure it has something to do with my own machine, of course, given that I had the program under a folder that OneDrive wanted to back up. And, I didn't want it there anymore because OneDrive is annoying. So, I deleted that version because of the problem. I re-downloaded the zip, extracted it in my _Downloads_ folder, opened it from there but the same thing - no IDE in sight.

**Comment by kittaakos** [comment]
Thanks for reporting it, @jetzoc. There should be a `config.json` file under `C:\Users\YOUR_NAME\AppData\Roaming\arduino-pro-ide`? Can you please share its content with us?

**Comment by kittaakos** [comment]
By the way, do you use multiple screens for your Windows env? Thanks!

**Comment by jetzoc** [comment]
Yes, of course, here are the contents. And, no, I don't use multiple screens; however, I do remember, changing the magnification levels on my display at one point but, I reverted the setting back to default. 

```
{
	"windowstate": {
		"isMaximized": false,
		"width": 968,
		"height": 781,
		"x": -20,
		"y": 1394
	}
}
```

**Comment by kittaakos** [comment]
Thank you! Could you please delete that file and see if it fixes the issue? (This file stores the location of the app on the screen.)

**Comment by jetzoc** [comment]
Okay, so I changed the ``is maximized`` parameter to ``true``. 
And, I was able to restore it. 

But, yes, I can delete the file as well. That works just the same

Thank you!

**Comment by kittaakos** [comment]
I am glad you could solve the issue.

I opened a follow-up here: https://github.com/arduino/arduino-pro-ide/issues/445
