### ISSUE TITLE
arduino-pro-ide_0.1.4_Windows_64bit - Window Resizing

### ISSUE THREAD

**Issue by ex-caliper** [arduino/arduino-pro-ide#448]
**Describe the bug**
When you try to resize from either height or width, the IDE automatically increases the **height** beyond the 
bottom of the screen. Subsequently the bottom of the console cannot be seen.

**To Reproduce**
Start the IDE as normal, try to reduce in anyway, height increases automatically beyond bottom of screen.
Further attempts at recovering the height can result in the IDE minimising to the task bar and cannot be restored.  It can be closed by right clicking the task bar icon, however, further attempts at restarting the IDE normally, automatically reduces it to the task bar rendering it unusable. 

**Expected behavior**
Resizing without issues mentioned.

**OS**: Windows 10 Pro
**Version:** 18363

**Additional context**
Further use of the IDE can only be achieved by deleting its folder and replacing with a fresh download.

**Comment by kittaakos** [comment]
Thank you, @ex-caliper. I have merged your bug report into https://github.com/arduino/arduino-pro-ide/issues/337#issuecomment-787763899.

Closing as duplicate.
