### ISSUE TITLE
Switching from classic mode to advanced mode close all open files. And vice-versa

### ISSUE THREAD

**Issue by Fede85** [arduino/arduino-pro-ide#47]
**Describe the bug**
When you have some files open in different tabs and you switch mode: `classic -> advanced` or `advanced -> classic` all the files are closed. 

**To Reproduce**
1. Open some files
2. toggle mode 

**Expected behavior**
I guess toggling mode should keep all files open

**Setup:**
 - OS: Windows
 - Version: 10

**Comment by kittaakos** [comment]
Same as: https://github.com/arduino/arduino-pro-ide/issues/101

The issue has been fixed and will be available with the next release.

**Comment by kittaakos** [comment]
Was fixed in `0.0.3`.
