### ISSUE TITLE
Advanced Mode: Open Folder is not working

### ISSUE THREAD

**Issue by Fede85** [arduino/arduino-pro-ide#48]
**Describe the bug**
I wanted to open a folder containing an Arduino sketch composed of multiple files. The sketch folder is not contained inside the sketchbook. I tried the "File > Open Folder" and after selecting the path and clicking on "Select directory" button a new IDE window has open but the folder I wanted to open didn't appear in the file system tree view.
Instead, in the new window I keep seeing the sketchbook directory

**To Reproduce**
1. Go to 'File > Open Folder...'
2. Select the path of a folder outside the "sketchboook"
3. Click on 'Select Directory' button
4. On the new IDE window check if the folder appears in the file system tree view

**Expected behavior**
Either the selected directory to appear in the file system view of the current open window or a new window containing only the selected directory.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version 10

**Comment by per1234** [comment]
Hi @Fede85 . Thanks so much for taking the time to report this!

The unnecessary **File > Open Folder** menu item has been removed. **File > Open** will now load all sketch files in the folder root when you open a sketch file, just as the classic Arduino IDE does.

If you like, you can try out [the new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4).

If you find any issues, or discover that the multi-file sketch handling is not working as you expect, please let us know.
