### ISSUE TITLE
Ubuntu Linux 18.04 and old arduino-cli

### ISSUE THREAD

**Issue by gdsports** [arduino/arduino-pro-ide#49]
I had an old version of arduino-cli on my ~/bin directory. arduino-electron ran that version instead of the one included with the Pro IDE. The problem is solved by removing ~/bin/arduino-cli and restarting the IDE.

**Comment by spoenemann** [comment]
We should show a warning and a hint for solving it if the version of the globally installed CLI is too old.

**Comment by kittaakos** [comment]
We pick the bundled CLI if it's version is more recent than the one from the `$PATH`. This is available since the `v0.0.3-alpha.preview` release.
