### ISSUE TITLE
macOS notarization is required for 10.15 (Catalina)

### ISSUE THREAD

**Issue by gvarisco** [arduino/arduino-pro-ide#5]
In order to run the PRO IDE on macOS Catalina (10.15), it's necessary to make sure the app is notarized. We may want to do this once CI/CD is set up for this target.

**Comment by kittaakos** [comment]
We have to sign the macOS build anyways if we want to support auto-updates for the app.
See: https://electronjs.org/docs/api/auto-updater#macos

**Comment by kittaakos** [comment]
The latest macOS app is signed and notarized. See: https://github.com/arduino/arduino-pro-ide/issues/304#issuecomment-680255852

@gvarisco, I am going to close this issue, please ping me if it still occurs.
