### ISSUE TITLE
doesn't open on Ubuntu 19.10

### ISSUE THREAD

**Issue by OMGdaDPS** [arduino/arduino-pro-ide#50]
I try to open the electron app for the IDE, after extracting, but it opens in my hex editor.

**Comment by mwz86** [comment]
run it usinig terminal
sudo (location)/arduino-electron
i tested it now its working

**Comment by OMGdaDPS** [comment]
omw

**Comment by OMGdaDPS** [comment]
yeah, that seems to work. I wonder why I was able to just double click it and it worked, on KDE Neon, but not on vanilla Ubuntu 19.10

**Comment by mwz86** [comment]
now i'm testing it 
there is some problems:
Failed to start arduino language package
Error: no core is installed for arduino uno #_#

**Comment by OMGdaDPS** [comment]
i was told to install clangd by using sudo snap install clangd --classic. it worked for me

**Comment by OMGdaDPS** [comment]
What did you do, just untar the archive and put it somewhere, go into the folder and double click the file labeled "arduino-electron"?

**Comment by OMGdaDPS** [comment]
I think it has something to do with maybe me installing a few other programs, and that has done something. Because like I said, it tries to open in my hex editor. I of course can choose a different program to try and open it with, but none have worked so far. The closest that I have gotten to it working was using "run software" in the "open in other application". It gives me a spinning "working in background circle, but the doesnt do anything.
   This is all of course, only on one of my machines. I have tested it on one other laptop so far, and it worked without a hitch on that one. I did exactly what I asked you if you had done.

**Comment by kittaakos** [comment]
> there is some problems:
> Failed to start arduino language package



> i was told to install clangd by using sudo snap install clangd --classic. it worked for me

I can confirm this with older versions. Now, we ship the app with `clangd` bundled into it.

> What did you do, just untar the archive and put it somewhere, go into the folder and double click the file labeled "arduino-electron"?

See [this thread](https://github.com/arduino/arduino-pro-ide/issues/160#issuecomment-561216286), @OMGdaDPS.

Please reopen if required.
