### ISSUE TITLE
getting problem while selecting port

### ISSUE THREAD

**Issue by zubairzati** [arduino/arduino-pro-ide#54]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by rsora** [comment]
Hi @zubairzati,
Could you please complete your bug report?

In the meantime, can you try the the following links and see if any of these Pro-IDE builds solve your problem?

osx: 
https://downloads.arduino.cc/arduino-pro-ide/snapshots/arduino-pro-ide-0.0.1-alpha.preview-snapshot-20191021.1-osx.dmg

linux:
https://downloads.arduino.cc/arduino-pro-ide/snapshots/arduino-pro-ide-0.0.1-alpha.preview-snapshot-20191021.1-linux64.tar.xz

windows:
https://downloads.arduino.cc/arduino-pro-ide/snapshots/arduino-pro-ide-0.0.1-alpha.preview-snapshot-20191021.1-windows.zip

**Comment by F-K-F-F** [comment]
Hi!
Linux build didn't work for me on Ubuntu 18.04.03. Still no port discovered.

**Comment by torenrl** [comment]
This works for me on macOS Catalina.

**Comment by zubairzati** [comment]
> Hi @zubairzati,
> Could you please complete your bug report?
> 
> In the meantime, can you try the the following links and see if any of these Pro-IDE builds solve your problem?
> 
> osx:
> https://downloads.arduino.cc/arduino-pro-ide/snapshots/arduino-pro-ide-0.0.1-alpha.preview-snapshot-20191021.1-osx.dmg
> 
> linux:
> https://downloads.arduino.cc/arduino-pro-ide/snapshots/arduino-pro-ide-0.0.1-alpha.preview-snapshot-20191021.1-linux64.tar.xz
> 
> windows:
> https://downloads.arduino.cc/arduino-pro-ide/snapshots/arduino-pro-ide-0.0.1-alpha.preview-snapshot-20191021.1-windows.zip

wishes for the day...
sir i have installed this one also but in windows i am not able to select board and port in arduino pro ide .

**Comment by mastrolinux** [comment]
Did you install at least one core to support your board?

**Comment by mastrolinux** [comment]
Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview please try again and give feedback

**Comment by F-K-F-F** [comment]
> Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview please try again and give feedback

Fixed on Ubuntu 18.04.03, board and port discovered automatically. Thank you!
