### ISSUE TITLE
Failed to start ide clang not found. - Ubuntu 

### ISSUE THREAD

**Issue by suryamurugan** [arduino/arduino-pro-ide#6]
Failed to start ide clang not found.

1. Loading the ide on ubuntu 16

 - OS: Ubuntu
 - Version 16.04

**Comment by naamah75** [comment]
Same issue here on Deepin 15.11

**Comment by mastrolinux** [comment]
This can be solved by:

`snap install clans --classic`

Can you please try it out and let us know?

**Comment by naamah75** [comment]
I' sorry but I cannot find the snap "clans".

**Comment by naamah75** [comment]
Installed snap "clangd", the problem seem to be solved.

**Comment by mastrolinux** [comment]
Update the comment, closing this for now.

**Comment by djsegfault** [comment]
As per #31 I tried "sudo apt-get install clang-tools-5.0" and that didn't fix it.  I also tried "sudo snap install clangd --classic" and that also didn't fix it. I got the same error

**Comment by jpeterse** [comment]
Getting the same error, even though Clang is already installed:

$ clang --version
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ locate clangd
/usr/bin/clangd-8
/usr/lib/llvm-8/bin/clangd

**Comment by notkevinjohn** [comment]
I got around this with the following steps on Ubuntu 19.04:

Install the clang tool package:
$ sudo apt-get install clang-tools-8


Specify the appropriate alternative for clangd
$ sudo update-alternatives --install /usr/bin/clangd clangd /usr/bin/clangd-8 100

These were instructions I found on clang's website:
https://clang.llvm.org/extra/clangd/Installation.html

**Comment by jpeterse** [comment]
I already had clang-tools installed, but didn't have a link from /usr/bin/clangd-8 to /usr/bin/clangd.
Adding the alternate option creates this link, and Arduino editor is now locating clangd.

**Comment by cwfitzgerald** [comment]
I set the `cpp.clangdExecutable` settings flag to `clangd-8` as I had clang-tools-8 installed, but it still reports a failure to start clangd.
