### ISSUE TITLE
ESP32 Dev module can't detect 

### ISSUE THREAD

**Issue by nomancyclewala** [arduino/arduino-pro-ide#61]
the normal Arduino ide easily detect ESP32 dev module but 
the new pro ide can't detecte it and say "no esp32 board is detected "

![Capture](https://user-images.githubusercontent.com/50193139/67203356-82b0ba00-f428-11e9-8edc-ba1bc65f3909.JPG)

**Comment by sirapol** [comment]
I can't upload to ESP32.

It's report like a picture.

![image](https://user-images.githubusercontent.com/7825850/67651553-28f24780-f974-11e9-9ed2-97a82ba21a73.png)

**Comment by hanif85** [comment]
![Capture](https://user-images.githubusercontent.com/17286008/85224575-8b152680-b3f5-11ea-8223-deb7f2a2e8ea.PNG)
just open arduino-cli.yaml and add [https://dl.espressif.com/dl/package_esp32_index.json](url)

**Comment by RoyHopkins** [comment]
Please explain how to install the ESP32in the Arduino Pro

**Comment by ubidefeo** [comment]
@RoyHopkins 
the comment just above yours tells you how
you need to add the index url to the configuration file and you'll be able to find the board in the Boards Manager

**Comment by kittaakos** [comment]
> Please explain how to install the ESP32in the Arduino Pro

See here: https://github.com/arduino/arduino-pro-ide/issues/245

I am going to close this issue, let me know if you want me to reopen but you can also create a new one.

**Comment by enavascalmell** [comment]
Hi, How do you install a Board esp32 on Arduino pro IDE?

**Comment by per1234** [comment]
@enavascalmell This issue tracker is only to be used to report bugs or feature requests. This is not the place to ask for support using the Pro IDE. This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
