### ISSUE TITLE
Make it open-source

### ISSUE THREAD

**Issue by DoodlesEpic** [arduino/arduino-pro-ide#64]
Let us contribute to the project, as-is development look slow, allowing for pull requests via Github or any other way to contribute would make the project develop much faster with a healthier community.

**Comment by joelvonrotz** [comment]
![grafik](https://user-images.githubusercontent.com/41155337/67224516-a4fb0580-f431-11e9-8391-2083db01ca6f.png)

Consider reading the blog post. They want to create the basics of the tool before releasing the source code.

**Comment by DoodlesEpic** [comment]
I've read it, I just wish the alpha version was also open-source.

**Comment by joelvonrotz** [comment]
> 
> 
> I've read it, I just wish the alpha version was also open-source.

oh alright, I apologize. Well I think they want to complete the alpha, as in include all the features they have planned. After the alpha and the release of the software, I'd imagine optimizations could be suggested.

**Comment by DoodlesEpic** [comment]
Sure, that does make sense, this topic has nothing to do so I'll just close it.
