### ISSUE TITLE
Examples menu missing Arduino Pro IDE

### ISSUE THREAD

**Issue by Erriez** [arduino/arduino-pro-ide#70]
The examples menu is not available in the File menu on Windows and Linux.

**New IDE:**
![image](https://user-images.githubusercontent.com/8849873/67231991-b0096200-f440-11e9-93de-4902e221df1e.png)

**Original IDE:**
![image](https://user-images.githubusercontent.com/8849873/67232092-dd561000-f440-11e9-9aac-896d5d2165ce.png)

What is the reason for this?

**Comment by tigoe** [comment]
+1 to this too. I use the File menu extensively in the original Arduino app, specifically the examples menu. Removing it is a step down from the previous app.

**Comment by minzukas** [comment]
following

**Comment by JeremySCook** [comment]
Would request this as well. 

Love where you're going with the IDE - should be awesome when done!

**Comment by Erriez** [comment]
The missing examples menu is one of the core features to quickly start a new project. Any news on this?

**Comment by Erriez** [comment]
Almost a year later after the first "pro" release, we still miss `Examples` and `History` from the `File` menu. When I create libraries for Arduino, I always spend a lot of time to include examples to demonstrate how the library / hardware works, but they are not visible.

Opening examples via the `File | Open` menu is really a pain, even in the latest version 0.1.1:

Let me explain our user experiences:

1. Opening examples looks like only possible via the `File | Open` menu and browse to a `.ino` file. This is time consuming, because double clicking on a `.ino` file in the `Nautilus` file manager does not work.
2. Bug: The serial port must be closed manually before opening the next `.ino` file, otherwise the serial port is still in use.
3. Bug: After opening the new `.ino` it displays: "Error: No boards selected. Please select a board.`. The IDE should remember the previous selected board.

Repeat these steps over and over again to switch between examples.

Can you please increase priority to implement a simple examples and history menu?

**Comment by kittaakos** [comment]
> Can you please increase priority to implement a simple examples

We're going to roll out a new release with the built-in examples in a few days. On top of that, we will also support library examples and the include library feature. Thanks for your patience and stay tuned.

**Comment by kittaakos** [comment]
It's available.
