### ISSUE TITLE
Change default sketches / libraries path

### ISSUE THREAD

**Issue by Erriez** [arduino/arduino-pro-ide#71]
How can I change the default libraries and sketches path on Windows 10? I can't find this in the preferences menu.

**Original IDE:**
![image](https://user-images.githubusercontent.com/8849873/67232765-4e49f780-f442-11e9-9f40-1d0fac40d095.png)

**Comment by kittaakos** [comment]
This will be available with the next, `0.0.6-alpha`, release. The Pro IDE will be fully compatible with the CLI configuration.

**Comment by kittaakos** [comment]
You can do it via the CLI configuration. `File` > `Settings` > `Open CLI Configuration` and change `directories.user` entry.
