### ISSUE TITLE
Board/Port not being detected

### ISSUE THREAD

**Issue by notkevinjohn** [arduino/arduino-pro-ide#75]
**Describe the bug**
I have an Arduino Mega connected to the computer. This board is successfully detected by the classic version of the Arduino IDE. The device is location at /dev/ttyACM0 on my computer. When I attempt to select the board, no port is detected. 

**To Reproduce**
1. Go to Board Manager
2. Install drivers for Arduino Mega AVR Boards
3. From board selection pull down, select Other Board & Port
4. Select Arduino Mega or Mega 2560
5. See Error

**Expected behavior**
The system would have allowed me to select the port /dev/ttyACM0

![image](https://user-images.githubusercontent.com/235216/67241161-c21ade80-f407-11e9-9fe0-1fb1c5e12361.png)

**Desktop (please complete the following information):**
 - Ubuntu Mate
 -  19.04

**Comment by rluberto** [comment]
The latest snapshot worked for me today (located below), however I am running Windows 10. 

[https://github.com/arduino/arduino-pro-ide/issues/54#issuecomment-544558918]

**Comment by rsora** [comment]
Hi @notkevinjohn, thanks for you bug report!

We just released the [build snapshot 20191021.1](https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.1-alpha.preview-snapshot-20191021.1)  in the release page, that includes board detection bugfixing. 

Can you try the new release and check if your issue is solved?

**Comment by notkevinjohn** [comment]
@rluberto rsora

Confirmed that this snapshot solves the issue I documented.

**Comment by mastrolinux** [comment]
Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview in even a better way.
