### ISSUE TITLE
"Include Library" Feature and Libraries not Being Recognized

### ISSUE THREAD

**Issue by rluberto** [arduino/arduino-pro-ide#76]
**It the feature related to a problem?**
Currently the IDE does not recognize any libraries that have been previously installed.

**Describe the solution you'd like**
An include library button similar to the current IDE.

**Additional context**
In the current Arduino IDE there is an "Include Library" button to include installed libraries and libraries like Servo.

Similar to #22

**Comment by per1234** [comment]
Hi @rluberto. Thanks so much for taking the time to request this important feature!

[The new 0.1.4 release of Arduino Pro IDE](https://github.com/arduino/arduino-pro-ide/releases/tag/0.1.4) has the requested **Sketch > Include library** menu, which will show all your installed libraries.
