### ISSUE TITLE
Problems with the label showing port connectivity

### ISSUE THREAD

**Issue by torenrl** [arduino/arduino-pro-ide#78]
**Describe the bug**
The port keeps becoming labelled as disconnected even though the connection seems to be in order.

**To Reproduce**
Steps to reproduce the behaviour:
1. Connect to a board/port
2. The board/port is labelled as connected and uploading sketches and serial port monitoring are both possible
3. The port is soon labeled as disconnected, even though the I am still able to upload sketches and monitor the serial port.

**Expected behaviour**
That the port is labelled as connected

**Screenshots**
![image](https://user-images.githubusercontent.com/3530623/67259341-00fb7380-f49e-11e9-9e6a-04d7ea05e46b.png)

**Desktop (please complete the following information):**
 - OS: macOS catalina
 - Version https://github.com/arduino/arduino-pro-ide/issues/54#issuecomment-544558918

**Comment by eclipse1985** [comment]
Same on `Mojave`

**Comment by mastrolinux** [comment]
Can you please try the new https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview version?

**Comment by torenrl** [comment]
Seems to be working now
