### ISSUE TITLE
C++ version

### ISSUE THREAD

**Issue by torenrl** [arduino/arduino-pro-ide#79]
Arduino is using the c++11  by default, and a manual compiler flag change is needed if c++14 or c++17 is needed. Could a more modern c++ version be set as the default, or could it be made easier to change it through the preferences?

**Comment by per1234** [comment]
This is something that would need to be implemented in the Arduino boards platform. The platform system allows each platform author the flexibility to define how it needs to work for their boards, which could have very different requirements depending on the architecture and toolchain. It is certainly possible to do via the existing platform framework, easily configurable by the user via a custom menu (e.g., **Tools > C++ Standard**. You can get see a working implementation of exactly that here:
https://github.com/MCUdude/MightyCore/pull/205
