### ISSUE TITLE
Can't Select the Board and Port

### ISSUE THREAD

**Issue by rluberto** [arduino/arduino-pro-ide#8]
The IDE opens and works properly however it is unable to discover the board and port.
Note: I installed the boards in the IDE however the boards I installed are still grayed out when trying to select a board.

**Steps to Reproduce**
1. Install the main Arduino boards in the IDE
2. Plug in board to computer
3. Select other board
4. No boards or ports are discovered

**Expected behavior**
Board or port is discovered

**Screenshots**
<img width="960" alt="Annotation 2019-10-19 123204" src="https://user-images.githubusercontent.com/21092717/67148315-87307380-f26c-11e9-9b53-ae97e47b7b3b.png">

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 64 bit
 - Version 10.0.18362

**Comment by OMGdaDPS** [comment]
same here. Able to install the needed stuff through the board manager, but the IDE doesnt find any ports. I am on Ubuntu 19.10, and have added myself to the dialout group of course

**Comment by rsora** [comment]
Hi there, thanks for your report!

Can you please check if the snapshot builds attached here https://github.com/arduino/arduino-pro-ide/issues/54#issuecomment-544558918 solve your detection problem?

Thanks!

**Comment by rluberto** [comment]
Yes that solved the problem!
