### ISSUE TITLE
Uninstall Boards

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#81]
It would helpful to have the possibility to uninstall boards. A button "Uninstall" similar to the "Install" button should added.

**Comment by sstaub** [comment]
The same for libraries.

**Comment by kittaakos** [comment]
Thank you for your bug report, @sstaub.

It has been implemented via https://github.com/arduino/arduino-pro-ide/issues/42 and will be available within the next `0.0.3` release. I am closing it as a duplicate.
