### ISSUE TITLE
Library Manager: scroll does not reset on search that returns less items

### ISSUE THREAD

**Issue by FrankGrimm** [arduino/arduino-pro-ide#82]
**Describe the bug**

**To Reproduce**
1. Click on "Sketch"
2. Click on 'Library Manager'
3. Scroll down using the mouse wheel.
4. In the search field enter a specific library name that only returns one result, e.g. "fastled".
5. The search result is not visible until you manually scroll up.

**Expected behavior**
The scroll state of the container should reset appropriately to show search results.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 18

**Additional context**
- It might also be a general bug with scrolling in that component, with larger search results I do not see a scroll bar on the right hand side while it is there in the bugged state.

**Comment by kittaakos** [comment]
Thank you for reporting the issue, @FrankGrimm. The fix is on the way and will be available with the next release.

![fastled](https://user-images.githubusercontent.com/1405703/68766143-98c42b80-061e-11ea-981c-97bb76e7ff65.gif)

**Comment by kittaakos** [comment]
Was fixed in `0.0.3`.
