### ISSUE TITLE
In normal mode: can not create new folder inside the workspace

### ISSUE THREAD

**Issue by cd643** [arduino/arduino-pro-ide#84]
When you are in the normal mode, I want to add folder to workspace but nothing happens.

1. go to the explorer in arduino pro
2. Click on add folder to workspace (more actions -> add folder to workspace)
3. select a folder

after this, there was no folder in my workspace but if I drag it to the workspace it works!

 - using linux xubuntu 18.04 LTS

**Comment by kittaakos** [comment]
> When you are in the normal mode, I want to add folder to workspace but nothing happens.

This behavior is expected. The normal mode has limitations; the workspace cannot be changed. We will disable this command to avoid confusion.

**Comment by jankeromnes** [comment]
I can take a look at this. @mastrolinux could you please assign me to this issue?

**Comment by jankeromnes** [comment]
I was able to reproduce this issue on Mac OS.

I believe the root problem is that in "non-advanced" mode, the File Explorer should not be visible at all.

On Mac at least, the Explorer is not visible by default in "non-advanced" mode. However, I found a "hack" to make the Explorer show up, by right-clicking on a editor tab handle, and clicking "Reveal":

<img width="1002" alt="Screenshot 2019-11-12 at 16 25 34" src="https://user-images.githubusercontent.com/599268/68684896-889e4480-0569-11ea-8ce1-8035f66f57fe.png">

<img width="1000" alt="Screenshot 2019-11-12 at 16 25 48" src="https://user-images.githubusercontent.com/599268/68684923-9227ac80-0569-11ea-918e-09d9e5a7c0b7.png">

I think that we should:
- Remove the "Reveal in Explorer" menu option in "non-advanced" mode
- Make sure that the Explorer can't show up in "non-advanced" mode

On the other hand, in "advanced" mode, "More Actions > Add Folder to Workspace" seems to work fine:

<img width="961" alt="Screenshot 2019-11-12 at 16 22 00" src="https://user-images.githubusercontent.com/599268/68685049-cbf8b300-0569-11ea-8abd-c220656f6fd0.png">

**Comment by kittaakos** [comment]
> 2\. Click on add folder to workspace (more actions -> add folder to workspace)

For the record:
 - `Add Folder to Workspace...` is a different thing.
 - We will add a menu item to `File` > `Create Folder` which will open the `Explorer` in classic mode and creates a new folder inside the current sketch dir.

**Comment by kittaakos** [comment]
The fix will be available in the next release.

![screencast 2019-11-21 15-09-16](https://user-images.githubusercontent.com/1405703/69345409-5bd8e400-0c71-11ea-8c94-f88ef834e115.gif)
