### ISSUE TITLE
How to set preferences?

### ISSUE THREAD

**Issue by cd643** [arduino/arduino-pro-ide#85]
How to set preferences in the editor such as you do in the 'old' ide.
I think it is a little bit complicated...

**Comment by j1mf** [comment]
Yes, I also find this aggravating. while the IDE installs on C:/, all of my projects and libraries are on F:/

**Comment by kittaakos** [comment]
> such as you do in the 'old' ide.

The new IDE supports settings the same way as the Java IDE.
