### ISSUE TITLE
Failed to start Arduino language server: jsonrpc2: connection is closed

### ISSUE THREAD

**Issue by satiowadahc** [arduino/arduino-pro-ide#88]
**Describe the bug**
Failed to start Arduino language server: jsonrpc2: connection is closed

**To Reproduce**
1. On Start Up, application either hangs indefinitely or reports Failed to start Language Server 

**Desktop (please complete the following information):**
 Windows 10 Build 18362 Clean install except GitKraken, Steam and Discord

**Comment by mastrolinux** [comment]
Please let us know what arduino-cli version you have, eventually update it and try again.

**Comment by mastrolinux** [comment]
Closing due to lack of info, feel free to comment again if you have more info.
