### ISSUE TITLE
No ports discovered

### ISSUE THREAD

**Issue by Durakill** [arduino/arduino-pro-ide#89]
**Describe the bug**
OS X Mojave - Earlier Arduino IDE working fine. However, after selecting Tools - Board Manger, Arduino Pro beta 0.1.1 reports “NO PORTS DISCOVERED”. Able to select board Uno OK.

**Expected behaviour**
Should allow display and selection of available port

**Desktop (please complete the following information):**
 - OS: OS X
 - Version 10.14.6

**Additional context**
Oh well.

**Comment by mastrolinux** [comment]
Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview
