### ISSUE TITLE
Sometimes the IDE doesn't start

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#90]
**Describe the bug**
The start of the IDE is very slow, sometimes never starts (see screenshot).
Sometimes you can see that the IDE UI is loaded for a short time, than the white screen comes
up, after a while (~6s on my MacBook Pro) the UI is ready but sometimes not.

**Expected behavior**
The startup time should much faster

**Screenshots**
<img width="1185" alt="IDE startup" src="https://user-images.githubusercontent.com/6450325/67372845-d8977600-f57e-11e9-8de0-033eddcd8dea.png">

**Desktop (please complete the following information):**
 - macOS Catalina
 - Version 0.0.1.20191021.1

**Comment by mastrolinux** [comment]
Can you also tell us if you have already an arduino-cli in your PATH? It could conflict if you have a version < 0.5.0. Eventually just remove your arduino-cli from the PATH.

type `which arduino-cli` in a terminal to verify if you have it in the PATH and `arduino-cli version` to check the version you have installed.

**Comment by sstaub** [comment]
In the terminal I get no response, wrong commands?
<img width="697" alt="Bildschirmfoto 2019-10-23 um 11 43 13" src="https://user-images.githubusercontent.com/6450325/67380246-5319c300-f58a-11e9-9035-2730019ac724.png">

**Comment by mastrolinux** [comment]
Please try again the v0.0.2 and let me know

**Comment by sstaub** [comment]
With 0.0.2 the IDE starts every time, the start up time for the GUI is now about 2s with a MacBook Pro 15'' 2018.

**Comment by mastrolinux** [comment]
So I will close this issue because now it is reliable. We will work later on performance but it is not something we will fix in the alpha phase. Thank you for the feedback.
