### ISSUE TITLE
No ports selected for board: NodeMCU

### ISSUE THREAD

**Issue by EfkanGuvenir** [arduino/arduino-pro-ide#93]
No ports selected for board: 'NodeMCU 1.0 (ESP-12E Module)'. I can't find the solution
![image](https://user-images.githubusercontent.com/34955853/67384669-48672a00-f59a-11e9-9a18-f15103cf0bea.png)

**Comment by mastrolinux** [comment]
Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview

**Comment by EfkanGuvenir** [comment]
Corrected by Https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview
