### ISSUE TITLE
Bare Metal Option

### ISSUE THREAD

**Issue by sstaub** [arduino/arduino-pro-ide#94]
**Describe the solution you'd like**
It would nice to have an option to program the Arduino boards without the Arduino framework.
This is possible in PlatformIO, because the #include of Arduino.h is not hidden.

**Comment by per1234** [comment]
Hi @sstaub. Even though I think the [Arduino sketch preprocessor](https://arduino.github.io/arduino-cli/latest/sketch-build-process/#pre-processing)'s default behavior of automatically adding the `#include` directive for `Arduino.h` to the .ino file is very important for providing beginners with a gentle learning curve, I also think it's nice to allow advanced users to have control over this. Cristian Maglie came up with what I think is the perfect solution to allow this: https://github.com/arduino/Arduino/issues/4352#issuecomment-174457395
>the preprocessor now skips the automatic insertion of the #include <Arduino.h> if the sketch already includes it.

You can combine this feature with a preprocessor conditional to prevent Arduino.h from being included in the sketch. People doing that might also find the ability to override the core library's `main()` to be handy:
```c++
#if false
#include <Arduino.h>
#endif

int main() {
  return 0;
}
```
