### ISSUE TITLE
i can see my installed board but i can't see any port

### ISSUE THREAD

**Issue by Master811129** [arduino/arduino-pro-ide#96]
**Describe the bug**
i can see my installed boards but i can't see any COM port in IDE.
v0.0.1-alpha.preview-snapshot-20191021.1

**To Reproduce**
1. Go to 'Arduino Pro IDE'
2. Click on 'boards and ports'

**Screenshots**
![image](https://user-images.githubusercontent.com/37829730/67517969-9e2df600-f6b0-11e9-9067-7d36166ac524.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10 enterprise]

**Comment by mastrolinux** [comment]
Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview

**Comment by Master811129** [comment]
> Should be fixed by https://github.com/arduino/arduino-pro-ide/releases/tag/v0.0.2-alpha.preview

yeah it fixed thank you🎉🎉🌭
