### ISSUE TITLE
Text color in dark Theme

### ISSUE THREAD

**Issue by fcebreros** [arduino/arduino-pro-ide#97]
On dark theme you don't se the white text on the white text boxes

Text should also be inverted

**Screenshots**
![imagen](https://user-images.githubusercontent.com/56903027/67531911-11704180-f68a-11e9-944f-90e050789ad5.png)

Windows 10.0.18362

**Comment by svenefftinge** [comment]
This is fixed in the upcoming milestone v0.0.3.

**Comment by kittaakos** [comment]
Was fixed in `0.0.3`.
