### ISSUE TITLE
Could not find Git on the PATH.

### ISSUE THREAD

**Issue by iotsharer** [arduino/arduino-pro-ide#99]
I can use git on shell,but when I open the arduino-pro-ide.It say Could not find Git on the PATH.
Why? And how to do ?(My OS is Win10 1903)
![image](https://user-images.githubusercontent.com/29347606/67567319-42b94200-f75c-11e9-9598-40bdb90c81c9.png)

![image](https://user-images.githubusercontent.com/29347606/67566979-9d9e6980-f75b-11e9-9287-0a619b5e97ab.png)

**Comment by kittaakos** [comment]
@iotsharer, where is your Git installed on Windows? This [issue](https://github.com/TypeFox/find-git-exec/issues/11) could be related. Thanks!

**Comment by iotsharer** [comment]
> @iotsharer, where is your Git installed on Windows? This [issue](https://github.com/TypeFox/find-git-exec/issues/11) could be related. Thanks!

I installed it in D:/Program Files/Git/ and I have set it to system Path.I can use git on powershell
![image](https://user-images.githubusercontent.com/29347606/67672171-51993200-f9b2-11e9-856b-f5837c60768a.png)
![image](https://user-images.githubusercontent.com/29347606/67672171-51993200-f9b2-11e9-856b-f5837c60768a.png)

**Comment by kittaakos** [comment]
Thanks for the details.

**Comment by tigoe** [comment]
Got this same issue on MacOS 10.14.6. The message showed up in a toast at the bottom of the screen and I can't make it go away. There is no indication in the UI of how to solve the issue.

**Comment by parasquid** [comment]
Just installed on Windows 10 and had the same toast message (found this issue after following the google links). I am however able to "make it go away" by clicking on the `x` mark in the toast.

Not sure what it's affecting though since I seem to be able to add board information just fine.

My git is found via:
```
git --info-path
C:/Users/tristan/scoop/apps/git/2.24.0.windows.2/mingw64/share/info
```

**Comment by kittaakos** [comment]
This has been resolved in Theia, we wait for npmjs to fix [an HTTP 503 issue](https://status.npmjs.org/incidents/gtjlhzsjqsyr) on their side.

**Comment by kittaakos** [comment]
This will be available in the next release.

**Comment by jankeromnes** [comment]
- [x] https://github.com/TypeFox/find-git-exec/issues/11 has been fixed
- [x] `find-git-exec` has been updated in Theia: https://github.com/eclipse-theia/theia/pull/6602
- [x] Theia has been updated in Arduino Pro IDE

I.e. this should be fixed now. Thanks for the great work!
